#!/bin/sh

case "$1" in
    "remove")
        service tomcat7 restart
        ;;
    "purge")
        rm -rf /etc/threadfix
        ;;
    "abort-install")
        service tomcat7 start
        ;;
    "abort-upgrade")
        service tomcat7 start
        ;;
esac

exit 0