var mime_samples = [
  { 'mime': 'application/binary', 'samples': [
    { 'url': 'http://demo.testfire.net/evil.swf', 'dir': '_m0/0', 'linked': 0, 'len': 142 } ]
  },
  { 'mime': 'application/javascript', 'samples': [
    { 'url': 'http://demo.testfire.net/bank/mozxpath.js', 'dir': '_m1/0', 'linked': 2, 'len': 1414 },
    { 'url': 'http://demo.testfire.net/pr/Draft.rtf', 'dir': '_m1/1', 'linked': 2, 'len': 11281 },
    { 'url': 'http://demo.testfire.net/pr/Q3_earnings.rtf', 'dir': '_m1/2', 'linked': 2, 'len': 187754 } ]
  },
  { 'mime': 'application/pdf', 'samples': [
    { 'url': 'http://demo.testfire.net/pr/communityannualreport.pdf', 'dir': '_m2/0', 'linked': 2, 'len': 63887 } ]
  },
  { 'mime': 'application/vnd.ms-excel', 'samples': [
    { 'url': 'http://demo.testfire.net/admin/clients.xls', 'dir': '_m3/0', 'linked': 0, 'len': 119296 } ]
  },
  { 'mime': 'application/x-shockwave-flash', 'samples': [
    { 'url': 'http://demo.testfire.net/subscribe.swf', 'dir': '_m4/0', 'linked': 2, 'len': 2484 } ]
  },
  { 'mime': 'application/xhtml+xml', 'samples': [
    { 'url': 'http://demo.testfire.net/', 'dir': '_m5/0', 'linked': 2, 'len': 9590 },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'dir': '_m5/1', 'linked': 2, 'len': 16822 },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'dir': '_m5/2', 'linked': 2, 'len': 8664 },
    { 'url': 'http://demo.testfire.net/admin/login.aspx', 'dir': '_m5/3', 'linked': 2, 'len': 8167 },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/', 'dir': '_m5/4', 'linked': 2, 'len': 3824 },
    { 'url': 'http://demo.testfire.net/bank/members/', 'dir': '_m5/5', 'linked': 2, 'len': 1656 },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'dir': '_m5/6', 'linked': 2, 'len': 5106 },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx', 'dir': '_m5/7', 'linked': 2, 'len': 3134 },
    { 'url': 'http://demo.testfire.net/comment.aspx', 'dir': '_m5/8', 'linked': 2, 'len': 7176 },
    { 'url': 'http://demo.testfire.net/default.aspx?content=inside_contact.htm', 'dir': '_m5/9', 'linked': 2, 'len': 10452 },
    { 'url': 'http://demo.testfire.net/default.aspx?content=00.htm', 'dir': '_m5/10', 'linked': 0, 'len': 4645 },
    { 'url': 'http://demo.testfire.net/feedback.aspx', 'dir': '_m5/11', 'linked': 2, 'len': 8666 },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx?step=a', 'dir': '_m5/12', 'linked': 2, 'len': 7731 },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'dir': '_m5/13', 'linked': 2, 'len': 21105 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=D:/downloads/AltoroMutual_v6/website/&del=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000467v138307\x3e', 'dir': '_m5/14', 'linked': 2, 'len': 4216 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C:', 'dir': '_m5/15', 'linked': 2, 'len': 5826 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://IISLogs', 'dir': '_m5/16', 'linked': 0, 'len': 2315 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://inetpub', 'dir': '_m5/17', 'linked': 0, 'len': 2747 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://Program%20Files', 'dir': '_m5/18', 'linked': 0, 'len': 6513 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://rs-pkgs', 'dir': '_m5/19', 'linked': 0, 'len': 5267 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://WINDOWS', 'dir': '_m5/20', 'linked': 0, 'len': 118913 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=D://downloads', 'dir': '_m5/21', 'linked': 0, 'len': 4990 },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=iisadmpwd', 'dir': '_m5/22', 'linked': 0, 'len': 3956 } ]
  },
  { 'mime': 'image/gif', 'samples': [
    { 'url': 'http://demo.testfire.net/images/adobe.gif', 'dir': '_m6/0', 'linked': 0, 'len': 1425 },
    { 'url': 'http://demo.testfire.net/images/altoro.gif', 'dir': '_m6/1', 'linked': 2, 'len': 4113 },
    { 'url': 'http://demo.testfire.net/images/logo.gif', 'dir': '_m6/2', 'linked': 2, 'len': 4989 },
    { 'url': 'http://demo.testfire.net/images/pf_lock.gif', 'dir': '_m6/3', 'linked': 2, 'len': 76 },
    { 'url': 'http://demo.testfire.net/images/spacer.gif', 'dir': '_m6/4', 'linked': 0, 'len': 43 } ]
  },
  { 'mime': 'image/jpeg', 'samples': [
    { 'url': 'http://demo.testfire.net/images/b_cards.jpg', 'dir': '_m7/0', 'linked': 0, 'len': 7235 },
    { 'url': 'http://demo.testfire.net/images/b_deposit.jpg', 'dir': '_m7/1', 'linked': 0, 'len': 6734 },
    { 'url': 'http://demo.testfire.net/images/b_insurance.jpg', 'dir': '_m7/2', 'linked': 0, 'len': 9195 },
    { 'url': 'http://demo.testfire.net/images/b_lending.jpg', 'dir': '_m7/3', 'linked': 0, 'len': 8481 },
    { 'url': 'http://demo.testfire.net/images/b_main.jpg', 'dir': '_m7/4', 'linked': 0, 'len': 8219 },
    { 'url': 'http://demo.testfire.net/images/b_other.jpg', 'dir': '_m7/5', 'linked': 0, 'len': 5701 },
    { 'url': 'http://demo.testfire.net/images/b_retirement.jpg', 'dir': '_m7/6', 'linked': 2, 'len': 6848 },
    { 'url': 'http://demo.testfire.net/images/header_pic.jpg', 'dir': '_m7/7', 'linked': 2, 'len': 16209 },
    { 'url': 'http://demo.testfire.net/images/home1.jpg', 'dir': '_m7/8', 'linked': 2, 'len': 7900 },
    { 'url': 'http://demo.testfire.net/images/home2.jpg', 'dir': '_m7/9', 'linked': 2, 'len': 5904 },
    { 'url': 'http://demo.testfire.net/images/home3.jpg', 'dir': '_m7/10', 'linked': 2, 'len': 10441 },
    { 'url': 'http://demo.testfire.net/images/inside1.jpg', 'dir': '_m7/11', 'linked': 0, 'len': 3697 },
    { 'url': 'http://demo.testfire.net/images/inside3.jpg', 'dir': '_m7/12', 'linked': 0, 'len': 7858 },
    { 'url': 'http://demo.testfire.net/images/inside4.jpg', 'dir': '_m7/13', 'linked': 0, 'len': 5477 },
    { 'url': 'http://demo.testfire.net/images/inside5.jpg', 'dir': '_m7/14', 'linked': 0, 'len': 4869 },
    { 'url': 'http://demo.testfire.net/images/inside6.jpg', 'dir': '_m7/15', 'linked': 2, 'len': 6573 },
    { 'url': 'http://demo.testfire.net/images/inside7.jpg', 'dir': '_m7/16', 'linked': 0, 'len': 8868 },
    { 'url': 'http://demo.testfire.net/images/p_cards.jpg', 'dir': '_m7/17', 'linked': 0, 'len': 9899 },
    { 'url': 'http://demo.testfire.net/images/p_checking.jpg', 'dir': '_m7/18', 'linked': 0, 'len': 8254 },
    { 'url': 'http://demo.testfire.net/images/p_deposit.jpg', 'dir': '_m7/19', 'linked': 0, 'len': 7170 },
    { 'url': 'http://demo.testfire.net/images/p_investments.jpg', 'dir': '_m7/20', 'linked': 0, 'len': 10631 },
    { 'url': 'http://demo.testfire.net/images/p_loans.jpg', 'dir': '_m7/21', 'linked': 0, 'len': 7740 },
    { 'url': 'http://demo.testfire.net/images/p_main.jpg', 'dir': '_m7/22', 'linked': 0, 'len': 8193 },
    { 'url': 'http://demo.testfire.net/images/p_other.jpg', 'dir': '_m7/23', 'linked': 0, 'len': 9095 } ]
  },
  { 'mime': 'image/x-ms-bmp', 'samples': [
    { 'url': 'http://demo.testfire.net/images/cancel.gif', 'dir': '_m8/0', 'linked': 2, 'len': 2598 } ]
  },
  { 'mime': 'text/css', 'samples': [
    { 'url': 'http://demo.testfire.net/style.css', 'dir': '_m9/0', 'linked': 2, 'len': 1198 } ]
  },
  { 'mime': 'text/html', 'samples': [
    { 'url': 'http://demo.testfire.net/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000139v138307\x3e', 'dir': '_m10/0', 'linked': 2, 'len': 34 },
    { 'url': 'http://demo.testfire.net/admin/', 'dir': '_m10/1', 'linked': 2, 'len': 218 },
    { 'url': 'http://demo.testfire.net/admin/nul.asmx/', 'dir': '_m10/2', 'linked': 0, 'len': 1510 },
    { 'url': 'http://demo.testfire.net/admin/captcha.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'dir': '_m10/3', 'linked': 2, 'len': 3026 },
    { 'url': 'http://demo.testfire.net/bank/', 'dir': '_m10/4', 'linked': 2, 'len': 2364 },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx', 'dir': '_m10/5', 'linked': 2, 'len': 3794 },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx?op=GetUserAccounts', 'dir': '_m10/6', 'linked': 2, 'len': 6773 },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx?op=IsValidUser', 'dir': '_m10/7', 'linked': 0, 'len': 6033 },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx?op=TransferBalance', 'dir': '_m10/8', 'linked': 0, 'len': 6982 },
    { 'url': 'http://demo.testfire.net/pr/', 'dir': '_m10/9', 'linked': 2, 'len': 584 },
    { 'url': 'http://demo.testfire.net/static/', 'dir': '_m10/10', 'linked': 2, 'len': 2528 },
    { 'url': 'http://demo.testfire.net/static/jobs/20061019.htm', 'dir': '_m10/11', 'linked': 1, 'len': 941 },
    { 'url': 'http://demo.testfire.net/static/jobs/20061023.htm', 'dir': '_m10/12', 'linked': 1, 'len': 1257 },
    { 'url': 'http://demo.testfire.net/static/jobs/20061024.htm', 'dir': '_m10/13', 'linked': 1, 'len': 862 },
    { 'url': 'http://demo.testfire.net/static/jobs/20061025.htm', 'dir': '_m10/14', 'linked': 1, 'len': 1224 },
    { 'url': 'http://demo.testfire.net/static/jobs/20061026.htm', 'dir': '_m10/15', 'linked': 1, 'len': 1302 },
    { 'url': 'http://demo.testfire.net/static/business.htm', 'dir': '_m10/16', 'linked': 0, 'len': 1675 },
    { 'url': 'http://demo.testfire.net/static/business_cards.htm', 'dir': '_m10/17', 'linked': 0, 'len': 1209 },
    { 'url': 'http://demo.testfire.net/static/business_deposit.htm', 'dir': '_m10/18', 'linked': 0, 'len': 1030 },
    { 'url': 'http://demo.testfire.net/static/business_insurance.htm', 'dir': '_m10/19', 'linked': 0, 'len': 888 },
    { 'url': 'http://demo.testfire.net/static/business_lending.htm', 'dir': '_m10/20', 'linked': 0, 'len': 1024 },
    { 'url': 'http://demo.testfire.net/static/inside.htm', 'dir': '_m10/21', 'linked': 0, 'len': 1541 },
    { 'url': 'http://demo.testfire.net/static/inside_about.htm', 'dir': '_m10/22', 'linked': 0, 'len': 1098 },
    { 'url': 'http://demo.testfire.net/static/inside_benefits.htm', 'dir': '_m10/23', 'linked': 0, 'len': 1775 },
    { 'url': 'http://demo.testfire.net/static/inside_careers.htm', 'dir': '_m10/24', 'linked': 0, 'len': 1489 },
    { 'url': 'http://demo.testfire.net/static/inside_community.htm', 'dir': '_m10/25', 'linked': 0, 'len': 1027 },
    { 'url': 'http://demo.testfire.net/static/inside_contact.htm', 'dir': '_m10/26', 'linked': 0, 'len': 3417 },
    { 'url': 'http://demo.testfire.net/static/inside_executives.htm', 'dir': '_m10/27', 'linked': 0, 'len': 3488 },
    { 'url': 'http://demo.testfire.net/static/inside_internships.htm', 'dir': '_m10/28', 'linked': 0, 'len': 781 },
    { 'url': 'http://demo.testfire.net/static/inside_investor.htm', 'dir': '_m10/29', 'linked': 0, 'len': 1463 },
    { 'url': 'http://demo.testfire.net/static/inside_jobs.htm', 'dir': '_m10/30', 'linked': 0, 'len': 3930 },
    { 'url': 'http://demo.testfire.net/static/inside_press.htm', 'dir': '_m10/31', 'linked': 0, 'len': 2473 },
    { 'url': 'http://demo.testfire.net/static/inside_trainee.htm', 'dir': '_m10/32', 'linked': 0, 'len': 1744 },
    { 'url': 'http://demo.testfire.net/static/personal.htm', 'dir': '_m10/33', 'linked': 0, 'len': 1773 },
    { 'url': 'http://demo.testfire.net/static/personal_checking.htm', 'dir': '_m10/34', 'linked': 0, 'len': 1237 },
    { 'url': 'http://demo.testfire.net/static/personal_deposit.htm', 'dir': '_m10/35', 'linked': 0, 'len': 1332 },
    { 'url': 'http://demo.testfire.net/static/personal_investments.htm', 'dir': '_m10/36', 'linked': 0, 'len': 1406 },
    { 'url': 'http://demo.testfire.net/static/personal_loans.htm', 'dir': '_m10/37', 'linked': 0, 'len': 979 },
    { 'url': 'http://demo.testfire.net/static/personal_other.htm', 'dir': '_m10/38', 'linked': 0, 'len': 986 },
    { 'url': 'http://demo.testfire.net/static/privacy.htm', 'dir': '_m10/39', 'linked': 0, 'len': 5819 },
    { 'url': 'http://demo.testfire.net/static/security.htm', 'dir': '_m10/40', 'linked': 2, 'len': 4530 },
    { 'url': 'http://demo.testfire.net/disclaimer.htm', 'dir': '_m10/41', 'linked': 2, 'len': 2083 },
    { 'url': 'http://demo.testfire.net/test.aspx', 'dir': '_m10/42', 'linked': 0, 'len': 558 } ]
  },
  { 'mime': 'text/plain', 'samples': [
    { 'url': 'http://demo.testfire.net/comments.txt', 'dir': '_m11/0', 'linked': 0, 'len': 37 },
    { 'url': 'http://demo.testfire.net/phpinfotest.txt', 'dir': '_m11/1', 'linked': 0, 'len': 19 },
    { 'url': 'http://demo.testfire.net/comments.aspx', 'dir': '_m11/2', 'linked': 0, 'len': 830 } ]
  },
  { 'mime': 'text/xml', 'samples': [
    { 'url': 'http://demo.testfire.net/bank/ws.asmx?disco', 'dir': '_m12/0', 'linked': 2, 'len': 731 },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx?WSDL', 'dir': '_m12/1', 'linked': 0, 'len': 8329 },
    { 'url': 'http://demo.testfire.net/pr/Docs.xml', 'dir': '_m12/2', 'linked': 2, 'len': 804 },
    { 'url': 'http://demo.testfire.net/static/business_retirement.htm', 'dir': '_m12/3', 'linked': 0, 'len': 98 } ]
  }
];

var issue_samples = [
  { 'severity': 3, 'type': 40402, 'samples': [
    { 'url': 'http://demo.testfire.net/admin/nul.asmx/', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/0' },
    { 'url': 'http://demo.testfire.net/admin/captcha.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/1' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/2' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/3' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/4' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/5' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/6' },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/7' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/8' },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/9' },
    { 'url': 'http://demo.testfire.net/comment.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/10' },
    { 'url': 'http://demo.testfire.net/comment.aspx/bank/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/11' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/12' },
    { 'url': 'http://demo.testfire.net/comment.aspx/images/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/13' },
    { 'url': 'http://demo.testfire.net/nul.asmx/', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/14' },
    { 'url': 'http://demo.testfire.net/static/default.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/15' },
    { 'url': 'http://demo.testfire.net/static/Privacypolicy.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/16' },
    { 'url': 'http://demo.testfire.net/comments.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/17' },
    { 'url': 'http://demo.testfire.net/default.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/18' },
    { 'url': 'http://demo.testfire.net/feedback.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/19' },
    { 'url': 'http://demo.testfire.net/search.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/20' },
    { 'url': 'http://demo.testfire.net/servererror.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/21' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/22' },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/23' },
    { 'url': 'http://demo.testfire.net/test.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'ASP.NET Yellow Screen of Death', 'dir': '_i1/24' } ]
  },
  { 'severity': 3, 'type': 40401, 'samples': [
    { 'url': 'http://demo.testfire.net/bank/', 'extra': 'Directory listing', 'dir': '_i2/0' },
    { 'url': 'http://demo.testfire.net/pr/', 'extra': 'Directory listing', 'dir': '_i2/1' },
    { 'url': 'http://demo.testfire.net/phpinfotest.txt', 'extra': 'PHP source', 'dir': '_i2/2' } ]
  },
  { 'severity': 3, 'type': 40305, 'samples': [
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i3/0' },
    { 'url': 'http://demo.testfire.net/comment.aspx', 'extra': '', 'dir': '_i3/1' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000023v138307\x3e', 'extra': '', 'dir': '_i3/2' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx', 'extra': '', 'dir': '_i3/3' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx', 'extra': '', 'dir': '_i3/4' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i3/5' },
    { 'url': 'http://demo.testfire.net/test1.aspx?get=http://skipfish.invalid/%3B%3F', 'extra': '', 'dir': '_i3/6' } ]
  },
  { 'severity': 3, 'type': 40201, 'samples': [
    { 'url': 'http://demo.testfire.net/static/personal_investments.htm', 'extra': 'http://demo-analytics.testfire.net/urchin.js', 'dir': '_i4/0' } ]
  },
  { 'severity': 3, 'type': 40101, 'samples': [
    { 'url': 'http://demo.testfire.net/comment.aspx', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'dir': '_i5/0' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000023v138307\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'dir': '_i5/1' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'dir': '_i5/2' } ]
  },
  { 'severity': 2, 'type': 30602, 'samples': [
    { 'url': 'http://demo.testfire.net/pr/Draft.rtf', 'extra': '', 'dir': '_i6/0' } ]
  },
  { 'severity': 2, 'type': 30601, 'samples': [
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/0' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/1' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/2' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/3' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/4' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/5' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/6' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/7' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/8' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/9' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/10' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/11' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/12' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/13' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/14' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/15' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/16' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/17' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/18' },
    { 'url': 'http://demo.testfire.net/search.aspx?txtSearch=skipfish', 'extra': '', 'dir': '_i7/19' } ]
  },
  { 'severity': 2, 'type': 30501, 'samples': [
    { 'url': 'http://demo.testfire.net/static/inside_benefits.htm', 'extra': 'http://www.exampledomainnotinuse.org/mybeacon.gif', 'dir': '_i8/0' },
    { 'url': 'http://demo.testfire.net/static/inside_contact.htm', 'extra': 'http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0', 'dir': '_i8/1' },
    { 'url': 'http://demo.testfire.net/static/personal.htm', 'extra': 'http://www.testfire.net/testfireappl/storefront/testfire_files/help_graphic.gif', 'dir': '_i8/2' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=inside_contact.htm', 'extra': 'http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0', 'dir': '_i8/3' },
    { 'url': 'http://demo.testfire.net/feedback.aspx', 'extra': 'http://www.altoromutual.com/bug.aspx', 'dir': '_i8/4' } ]
  },
  { 'severity': 1, 'type': 20205, 'samples': [
    { 'url': 'http://demo.testfire.net/survey_questions.aspx?step=a', 'extra': '', 'dir': '_i9/0' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i9/1' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i9/2' } ]
  },
  { 'severity': 1, 'type': 20101, 'samples': [
    { 'url': 'http://demo.testfire.net/admin/nul.asmx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'during URL injection attacks', 'dir': '_i10/0' },
    { 'url': 'http://demo.testfire.net/nul.asmx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': 'during URL injection attacks', 'dir': '_i10/1' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=s110ql', 'extra': 'during parameter brute-force tests', 'dir': '_i10/2' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://wamp', 'extra': 'during try list fetches', 'dir': '_i10/3' } ]
  },
  { 'severity': 0, 'type': 10901, 'samples': [
    { 'url': 'http://demo.testfire.net/%2Fnotfound.aspx%3Faspxerrorpath%3D%2Fsfi9876.asmx/', 'extra': '', 'dir': '_i11/0' },
    { 'url': 'http://demo.testfire.net/bank/20060308_bak/', 'extra': '', 'dir': '_i11/1' },
    { 'url': 'http://demo.testfire.net/pr/Q3_earnings.rtf', 'extra': '', 'dir': '_i11/2' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061019.htm', 'extra': '', 'dir': '_i11/3' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061023.htm', 'extra': '', 'dir': '_i11/4' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061024.htm', 'extra': '', 'dir': '_i11/5' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061025.htm', 'extra': '', 'dir': '_i11/6' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061026.htm', 'extra': '', 'dir': '_i11/7' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i11/8' } ]
  },
  { 'severity': 0, 'type': 10804, 'samples': [
    { 'url': 'http://demo.testfire.net/', 'extra': '', 'dir': '_i12/0' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx', 'extra': '', 'dir': '_i12/1' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx', 'extra': '', 'dir': '_i12/2' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/', 'extra': '', 'dir': '_i12/3' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/', 'extra': '', 'dir': '_i12/4' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i12/5' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i12/6' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i12/7' },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx', 'extra': '', 'dir': '_i12/8' },
    { 'url': 'http://demo.testfire.net/comment.aspx/', 'extra': '', 'dir': '_i12/9' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx?content=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000057v138307\x3e', 'extra': '', 'dir': '_i12/10' },
    { 'url': 'http://demo.testfire.net/comment.aspx', 'extra': '', 'dir': '_i12/11' },
    { 'url': 'http://demo.testfire.net/comment.aspx', 'extra': '', 'dir': '_i12/12' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=inside_contact.htm', 'extra': '', 'dir': '_i12/13' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=00.htm', 'extra': '', 'dir': '_i12/14' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=default.htm', 'extra': '', 'dir': '_i12/15' },
    { 'url': 'http://demo.testfire.net/feedback.aspx', 'extra': '', 'dir': '_i12/16' },
    { 'url': 'http://demo.testfire.net/search.aspx', 'extra': '', 'dir': '_i12/17' },
    { 'url': 'http://demo.testfire.net/servererror.aspx', 'extra': '', 'dir': '_i12/18' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx', 'extra': '', 'dir': '_i12/19' },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx', 'extra': '', 'dir': '_i12/20' },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx?step=a', 'extra': '', 'dir': '_i12/21' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=D:/downloads/AltoroMutual_v6/website/&del=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000467v138307\x3e', 'extra': '', 'dir': '_i12/22' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000582v138307\x3e', 'extra': '', 'dir': '_i12/23' },
    { 'url': 'http://demo.testfire.net/test1.aspx?get=D:/downloads/AltoroMutual_v6/website//Acomments.txtB', 'extra': '', 'dir': '_i12/24' } ]
  },
  { 'severity': 0, 'type': 10803, 'samples': [
    { 'url': 'http://demo.testfire.net/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000139v138307\x3e', 'extra': '', 'dir': '_i13/0' },
    { 'url': 'http://demo.testfire.net/%2Fnotfound.aspx%3Faspxerrorpath%3D%2Fsfi9876.asmx/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000000v138307\x3e', 'extra': '', 'dir': '_i13/1' },
    { 'url': 'http://demo.testfire.net/admin/', 'extra': '', 'dir': '_i13/2' },
    { 'url': 'http://demo.testfire.net/admin/CustomerServiceRepresentative:CustomerService.asmx/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000400v138307\x3e', 'extra': '', 'dir': '_i13/3' },
    { 'url': 'http://demo.testfire.net/admin/nul.asmx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000423v138307\x3e', 'extra': '', 'dir': '_i13/4' },
    { 'url': 'http://demo.testfire.net/admin/clients.xls/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000399v138307\x3e', 'extra': '', 'dir': '_i13/5' },
    { 'url': 'http://demo.testfire.net/admin/captcha.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000439v138307\x3e', 'extra': '', 'dir': '_i13/6' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000449v138307\x3e', 'extra': '', 'dir': '_i13/7' },
    { 'url': 'http://demo.testfire.net/bank/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000053v138307\x3e', 'extra': '', 'dir': '_i13/8' },
    { 'url': 'http://demo.testfire.net/bank/20060308_bak/', 'extra': '', 'dir': '_i13/9' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000096v138307\x3e', 'extra': '', 'dir': '_i13/10' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/login.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000099v138307\x3e', 'extra': '', 'dir': '_i13/11' },
    { 'url': 'http://demo.testfire.net/bank/images/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000091v138307\x3e', 'extra': '', 'dir': '_i13/12' },
    { 'url': 'http://demo.testfire.net/bank/members/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000095v138307\x3e', 'extra': '', 'dir': '_i13/13' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000107v138307\x3e', 'extra': '', 'dir': '_i13/14' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/login.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000109v138307\x3e', 'extra': '', 'dir': '_i13/15' },
    { 'url': 'http://demo.testfire.net/bank/mozxpath.js', 'extra': '', 'dir': '_i13/16' },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000005v138307\x3e', 'extra': '', 'dir': '_i13/17' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000115v138307\x3e', 'extra': '', 'dir': '_i13/18' },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000103v138307\x3e', 'extra': '', 'dir': '_i13/19' },
    { 'url': 'http://demo.testfire.net/comment.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000027v138307\x3e', 'extra': '', 'dir': '_i13/20' },
    { 'url': 'http://demo.testfire.net/comment.aspx/bank/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000033v138307\x3e', 'extra': '', 'dir': '_i13/21' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000049v138307\x3e', 'extra': '', 'dir': '_i13/22' },
    { 'url': 'http://demo.testfire.net/comment.aspx/images/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000043v138307\x3e', 'extra': '', 'dir': '_i13/23' },
    { 'url': 'http://demo.testfire.net/CustomerServiceRepresentative:CustomerService.asmx/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000332v138307\x3e', 'extra': '', 'dir': '_i13/24' },
    { 'url': 'http://demo.testfire.net/images/', 'extra': '', 'dir': '_i13/25' },
    { 'url': 'http://demo.testfire.net/images/adobe.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001079v138307\x3e', 'extra': '', 'dir': '_i13/26' },
    { 'url': 'http://demo.testfire.net/images/altoro.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000329v138307\x3e', 'extra': '', 'dir': '_i13/27' },
    { 'url': 'http://demo.testfire.net/images/b_cards.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001053v138307\x3e', 'extra': '', 'dir': '_i13/28' },
    { 'url': 'http://demo.testfire.net/images/b_deposit.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001083v138307\x3e', 'extra': '', 'dir': '_i13/29' },
    { 'url': 'http://demo.testfire.net/images/b_insurance.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001073v138307\x3e', 'extra': '', 'dir': '_i13/30' },
    { 'url': 'http://demo.testfire.net/images/b_lending.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001069v138307\x3e', 'extra': '', 'dir': '_i13/31' },
    { 'url': 'http://demo.testfire.net/images/b_main.jpg/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001084v138307\x3e', 'extra': '', 'dir': '_i13/32' },
    { 'url': 'http://demo.testfire.net/images/b_other.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001065v138307\x3e', 'extra': '', 'dir': '_i13/33' },
    { 'url': 'http://demo.testfire.net/images/b_retirement.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001023v138307\x3e', 'extra': '', 'dir': '_i13/34' },
    { 'url': 'http://demo.testfire.net/images/cancel.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000119v138307\x3e', 'extra': '', 'dir': '_i13/35' },
    { 'url': 'http://demo.testfire.net/images/header_pic.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000133v138307\x3e', 'extra': '', 'dir': '_i13/36' },
    { 'url': 'http://demo.testfire.net/images/home1.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000125v138307\x3e', 'extra': '', 'dir': '_i13/37' },
    { 'url': 'http://demo.testfire.net/images/home2.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000129v138307\x3e', 'extra': '', 'dir': '_i13/38' },
    { 'url': 'http://demo.testfire.net/images/home3.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000127v138307\x3e', 'extra': '', 'dir': '_i13/39' },
    { 'url': 'http://demo.testfire.net/images/inside1.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001067v138307\x3e', 'extra': '', 'dir': '_i13/40' },
    { 'url': 'http://demo.testfire.net/images/inside3.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001077v138307\x3e', 'extra': '', 'dir': '_i13/41' },
    { 'url': 'http://demo.testfire.net/images/inside4.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001057v138307\x3e', 'extra': '', 'dir': '_i13/42' },
    { 'url': 'http://demo.testfire.net/images/inside5.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001049v138307\x3e', 'extra': '', 'dir': '_i13/43' },
    { 'url': 'http://demo.testfire.net/images/inside6.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000121v138307\x3e', 'extra': '', 'dir': '_i13/44' },
    { 'url': 'http://demo.testfire.net/images/inside7.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001059v138307\x3e', 'extra': '', 'dir': '_i13/45' },
    { 'url': 'http://demo.testfire.net/images/logo.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000137v138307\x3e', 'extra': '', 'dir': '_i13/46' },
    { 'url': 'http://demo.testfire.net/images/p_cards.jpg/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001060v138307\x3e', 'extra': '', 'dir': '_i13/47' },
    { 'url': 'http://demo.testfire.net/images/p_checking.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001047v138307\x3e', 'extra': '', 'dir': '_i13/48' },
    { 'url': 'http://demo.testfire.net/images/p_deposit.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001075v138307\x3e', 'extra': '', 'dir': '_i13/49' },
    { 'url': 'http://demo.testfire.net/images/p_investments.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001087v138307\x3e', 'extra': '', 'dir': '_i13/50' },
    { 'url': 'http://demo.testfire.net/images/p_loans.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001063v138307\x3e', 'extra': '', 'dir': '_i13/51' },
    { 'url': 'http://demo.testfire.net/images/p_main.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001071v138307\x3e', 'extra': '', 'dir': '_i13/52' },
    { 'url': 'http://demo.testfire.net/images/p_other.jpg/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001055v138307\x3e', 'extra': '', 'dir': '_i13/53' },
    { 'url': 'http://demo.testfire.net/images/pf_lock.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000135v138307\x3e', 'extra': '', 'dir': '_i13/54' },
    { 'url': 'http://demo.testfire.net/images/spacer.gif/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001081v138307\x3e', 'extra': '', 'dir': '_i13/55' },
    { 'url': 'http://demo.testfire.net/nul.asmx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000453v138307\x3e', 'extra': '', 'dir': '_i13/56' },
    { 'url': 'http://demo.testfire.net/pr/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000347v138307\x3e', 'extra': '', 'dir': '_i13/57' },
    { 'url': 'http://demo.testfire.net/pr/communityannualreport.pdf/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000341v138307\x3e', 'extra': '', 'dir': '_i13/58' },
    { 'url': 'http://demo.testfire.net/pr/Docs.xml', 'extra': '', 'dir': '_i13/59' },
    { 'url': 'http://demo.testfire.net/pr/Draft.rtf', 'extra': '', 'dir': '_i13/60' },
    { 'url': 'http://demo.testfire.net/pr/Q3_earnings.rtf', 'extra': '', 'dir': '_i13/61' },
    { 'url': 'http://demo.testfire.net/rss/', 'extra': '', 'dir': '_i13/62' },
    { 'url': 'http://demo.testfire.net/static/', 'extra': '', 'dir': '_i13/63' },
    { 'url': 'http://demo.testfire.net/static/admin/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000221v138307\x3e', 'extra': '', 'dir': '_i13/64' },
    { 'url': 'http://demo.testfire.net/static/images/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000149v138307\x3e', 'extra': '', 'dir': '_i13/65' },
    { 'url': 'http://demo.testfire.net/static/jobs/', 'extra': '', 'dir': '_i13/66' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061019.htm', 'extra': '', 'dir': '_i13/67' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061023.htm', 'extra': '', 'dir': '_i13/68' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061024.htm', 'extra': '', 'dir': '_i13/69' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061025.htm', 'extra': '', 'dir': '_i13/70' },
    { 'url': 'http://demo.testfire.net/static/jobs/20061026.htm', 'extra': '', 'dir': '_i13/71' },
    { 'url': 'http://demo.testfire.net/static/pr/', 'extra': '', 'dir': '_i13/72' },
    { 'url': 'http://demo.testfire.net/static/business.htm', 'extra': '', 'dir': '_i13/73' },
    { 'url': 'http://demo.testfire.net/static/business_cards.htm', 'extra': '', 'dir': '_i13/74' },
    { 'url': 'http://demo.testfire.net/static/business_deposit.htm', 'extra': '', 'dir': '_i13/75' },
    { 'url': 'http://demo.testfire.net/static/business_insurance.htm', 'extra': '', 'dir': '_i13/76' },
    { 'url': 'http://demo.testfire.net/static/business_lending.htm', 'extra': '', 'dir': '_i13/77' },
    { 'url': 'http://demo.testfire.net/static/business_retirement.htm', 'extra': '', 'dir': '_i13/78' },
    { 'url': 'http://demo.testfire.net/static/default.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000151v138307\x3e', 'extra': '', 'dir': '_i13/79' },
    { 'url': 'http://demo.testfire.net/static/default.htm/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000161v138307\x3e', 'extra': '', 'dir': '_i13/80' },
    { 'url': 'http://demo.testfire.net/static/disclaimer.htm/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000215v138307\x3e', 'extra': '', 'dir': '_i13/81' },
    { 'url': 'http://demo.testfire.net/static/inside.htm', 'extra': '', 'dir': '_i13/82' },
    { 'url': 'http://demo.testfire.net/static/inside_about.htm', 'extra': '', 'dir': '_i13/83' },
    { 'url': 'http://demo.testfire.net/static/inside_benefits.htm', 'extra': '', 'dir': '_i13/84' },
    { 'url': 'http://demo.testfire.net/static/inside_careers.htm', 'extra': '', 'dir': '_i13/85' },
    { 'url': 'http://demo.testfire.net/static/inside_community.htm', 'extra': '', 'dir': '_i13/86' },
    { 'url': 'http://demo.testfire.net/static/inside_contact.htm', 'extra': '', 'dir': '_i13/87' },
    { 'url': 'http://demo.testfire.net/static/inside_executives.htm', 'extra': '', 'dir': '_i13/88' },
    { 'url': 'http://demo.testfire.net/static/inside_internships.htm', 'extra': '', 'dir': '_i13/89' },
    { 'url': 'http://demo.testfire.net/static/inside_investor.htm', 'extra': '', 'dir': '_i13/90' },
    { 'url': 'http://demo.testfire.net/static/inside_jobs.htm', 'extra': '', 'dir': '_i13/91' },
    { 'url': 'http://demo.testfire.net/static/inside_press.htm', 'extra': '', 'dir': '_i13/92' },
    { 'url': 'http://demo.testfire.net/static/inside_trainee.htm', 'extra': '', 'dir': '_i13/93' },
    { 'url': 'http://demo.testfire.net/static/personal.htm', 'extra': '', 'dir': '_i13/94' },
    { 'url': 'http://demo.testfire.net/static/personal_checking.htm', 'extra': '', 'dir': '_i13/95' },
    { 'url': 'http://demo.testfire.net/static/personal_deposit.htm', 'extra': '', 'dir': '_i13/96' },
    { 'url': 'http://demo.testfire.net/static/personal_investments.htm', 'extra': '', 'dir': '_i13/97' },
    { 'url': 'http://demo.testfire.net/static/personal_loans.htm', 'extra': '', 'dir': '_i13/98' },
    { 'url': 'http://demo.testfire.net/static/personal_other.htm', 'extra': '', 'dir': '_i13/99' },
    { 'url': 'http://demo.testfire.net/static/privacy.htm', 'extra': '', 'dir': '_i13/100' },
    { 'url': 'http://demo.testfire.net/static/Privacypolicy.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000237v138307\x3e', 'extra': '', 'dir': '_i13/101' },
    { 'url': 'http://demo.testfire.net/static/security.htm', 'extra': '', 'dir': '_i13/102' },
    { 'url': 'http://demo.testfire.net/transfer/', 'extra': '', 'dir': '_i13/103' },
    { 'url': 'http://demo.testfire.net/comments.txt', 'extra': '', 'dir': '_i13/104' },
    { 'url': 'http://demo.testfire.net/disclaimer.htm/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000017v138307\x3e', 'extra': '', 'dir': '_i13/105' },
    { 'url': 'http://demo.testfire.net/evil.swf/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001011v138307\x3e', 'extra': '', 'dir': '_i13/106' },
    { 'url': 'http://demo.testfire.net/high_yield_investments.htm', 'extra': '', 'dir': '_i13/107' },
    { 'url': 'http://demo.testfire.net/phpinfotest.txt', 'extra': '', 'dir': '_i13/108' },
    { 'url': 'http://demo.testfire.net/style.css', 'extra': '', 'dir': '_i13/109' },
    { 'url': 'http://demo.testfire.net/subscribe.swf/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000013v138307\x3e', 'extra': '', 'dir': '_i13/110' },
    { 'url': 'http://demo.testfire.net/comments.aspx/--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001050v138307\x3e', 'extra': '', 'dir': '_i13/111' },
    { 'url': 'http://demo.testfire.net/default.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000021v138307\x3e', 'extra': '', 'dir': '_i13/112' },
    { 'url': 'http://demo.testfire.net/feedback.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000063v138307\x3e', 'extra': '', 'dir': '_i13/113' },
    { 'url': 'http://demo.testfire.net/search.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000015v138307\x3e', 'extra': '', 'dir': '_i13/114' },
    { 'url': 'http://demo.testfire.net/servererror.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001019v138307\x3e', 'extra': '', 'dir': '_i13/115' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000363v138307\x3e', 'extra': '', 'dir': '_i13/116' },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000009v138307\x3e', 'extra': '', 'dir': '_i13/117' },
    { 'url': 'http://demo.testfire.net/test.aspx/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi001017v138307\x3e', 'extra': '', 'dir': '_i13/118' } ]
  },
  { 'severity': 0, 'type': 10802, 'samples': [
    { 'url': 'http://demo.testfire.net/comments.txt', 'extra': 'text/plain', 'dir': '_i14/0' },
    { 'url': 'http://demo.testfire.net/phpinfotest.txt', 'extra': 'text/plain', 'dir': '_i14/1' } ]
  },
  { 'severity': 0, 'type': 10801, 'samples': [
    { 'url': 'http://demo.testfire.net/images/cancel.gif', 'extra': 'image/x-ms-bmp', 'dir': '_i15/0' },
    { 'url': 'http://demo.testfire.net/pr/Draft.rtf', 'extra': 'application/javascript', 'dir': '_i15/1' },
    { 'url': 'http://demo.testfire.net/pr/Q3_earnings.rtf', 'extra': 'application/javascript', 'dir': '_i15/2' },
    { 'url': 'http://demo.testfire.net/static/business_retirement.htm', 'extra': 'text/xml', 'dir': '_i15/3' },
    { 'url': 'http://demo.testfire.net/evil.swf', 'extra': 'application/binary', 'dir': '_i15/4' },
    { 'url': 'http://demo.testfire.net/comments.aspx', 'extra': 'text/plain', 'dir': '_i15/5' } ]
  },
  { 'severity': 0, 'type': 10603, 'samples': [
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i16/0' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i16/1' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i16/2' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C:', 'extra': '', 'dir': '_i16/3' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://IISLogs', 'extra': '', 'dir': '_i16/4' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://inetpub', 'extra': '', 'dir': '_i16/5' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://Program%20Files', 'extra': '', 'dir': '_i16/6' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://rs-pkgs', 'extra': '', 'dir': '_i16/7' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=C://WINDOWS', 'extra': '', 'dir': '_i16/8' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=D://downloads', 'extra': '', 'dir': '_i16/9' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=iisadmpwd', 'extra': '', 'dir': '_i16/10' } ]
  },
  { 'severity': 0, 'type': 10602, 'samples': [
    { 'url': 'http://demo.testfire.net/admin/login.aspx', 'extra': '', 'dir': '_i17/0' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i17/1' } ]
  },
  { 'severity': 0, 'type': 10505, 'samples': [
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': 'txtCmdIn', 'dir': '_i18/0' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': 'uid', 'dir': '_i18/1' } ]
  },
  { 'severity': 0, 'type': 10403, 'samples': [
    { 'url': 'http://demo.testfire.net/admin/captcha.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/0' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/1' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/', 'extra': '', 'dir': '_i19/2' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/login.aspx/', 'extra': '', 'dir': '_i19/3' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/', 'extra': '', 'dir': '_i19/4' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/login.aspx/', 'extra': '', 'dir': '_i19/5' },
    { 'url': 'http://demo.testfire.net/bank/ws.asmx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/6' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/7' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': '', 'dir': '_i19/8' },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/9' },
    { 'url': 'http://demo.testfire.net/comment.aspx/', 'extra': '', 'dir': '_i19/10' },
    { 'url': 'http://demo.testfire.net/comment.aspx/bank/', 'extra': '', 'dir': '_i19/11' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx/', 'extra': '', 'dir': '_i19/12' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx?content=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000057v138307\x3e', 'extra': '', 'dir': '_i19/13' },
    { 'url': 'http://demo.testfire.net/comment.aspx/images/', 'extra': '', 'dir': '_i19/14' },
    { 'url': 'http://demo.testfire.net/static/default.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/15' },
    { 'url': 'http://demo.testfire.net/static/Privacypolicy.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/16' },
    { 'url': 'http://demo.testfire.net/comments.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/17' },
    { 'url': 'http://demo.testfire.net/default.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/18' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=.../inside_contact.htm', 'extra': '', 'dir': '_i19/19' },
    { 'url': 'http://demo.testfire.net/default.aspx?content=00.htm', 'extra': '', 'dir': '_i19/20' },
    { 'url': 'http://demo.testfire.net/feedback.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/21' },
    { 'url': 'http://demo.testfire.net/search.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/22' },
    { 'url': 'http://demo.testfire.net/servererror.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/23' },
    { 'url': 'http://demo.testfire.net/subscribe.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/24' },
    { 'url': 'http://demo.testfire.net/survey_questions.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/25' },
    { 'url': 'http://demo.testfire.net/test.aspx/%2F%2Fskipfish.invalid%2F%3B%3F', 'extra': '', 'dir': '_i19/26' },
    { 'url': 'http://demo.testfire.net/test1.aspx', 'extra': '', 'dir': '_i19/27' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=D:/downloads/AltoroMutual_v6/website/&del=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000467v138307\x3e', 'extra': '', 'dir': '_i19/28' },
    { 'url': 'http://demo.testfire.net/test1.aspx?fdir=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000582v138307\x3e', 'extra': '', 'dir': '_i19/29' },
    { 'url': 'http://demo.testfire.net/test1.aspx?get=D:/downloads/AltoroMutual_v6/website//Acomments.txtB', 'extra': '', 'dir': '_i19/30' } ]
  },
  { 'severity': 0, 'type': 10402, 'samples': [
    { 'url': 'http://demo.testfire.net/bank/members/', 'extra': '', 'dir': '_i20/0' } ]
  },
  { 'severity': 0, 'type': 10401, 'samples': [
    { 'url': 'http://demo.testfire.net/%2Fnotfound.aspx%3Faspxerrorpath%3D%2Fsfi9876.asmx/', 'extra': '', 'dir': '_i21/0' },
    { 'url': 'http://demo.testfire.net/admin/CustomerServiceRepresentative:CustomerService.asmx/', 'extra': '', 'dir': '_i21/1' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/', 'extra': '', 'dir': '_i21/2' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/login.aspx/', 'extra': '', 'dir': '_i21/3' },
    { 'url': 'http://demo.testfire.net/bank/members/', 'extra': '', 'dir': '_i21/4' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/', 'extra': '', 'dir': '_i21/5' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/login.aspx/', 'extra': '', 'dir': '_i21/6' },
    { 'url': 'http://demo.testfire.net/comment.aspx/', 'extra': '', 'dir': '_i21/7' },
    { 'url': 'http://demo.testfire.net/comment.aspx/bank/', 'extra': '', 'dir': '_i21/8' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx/', 'extra': '', 'dir': '_i21/9' },
    { 'url': 'http://demo.testfire.net/comment.aspx/default.aspx?content=inside_contact.htm', 'extra': '', 'dir': '_i21/10' },
    { 'url': 'http://demo.testfire.net/comment.aspx/images/', 'extra': '', 'dir': '_i21/11' },
    { 'url': 'http://demo.testfire.net/CustomerServiceRepresentative:CustomerService.asmx/', 'extra': '', 'dir': '_i21/12' },
    { 'url': 'http://demo.testfire.net/test1.aspx?get=D:/downloads/AltoroMutual_v6/website//Acomments.txtB', 'extra': '', 'dir': '_i21/13' } ]
  },
  { 'severity': 0, 'type': 10205, 'samples': [
    { 'url': 'http://demo.testfire.net/sfi9876.asmx', 'extra': '', 'dir': '_i22/0' },
    { 'url': 'http://demo.testfire.net/sfi9876', 'extra': '', 'dir': '_i22/1' },
    { 'url': 'http://demo.testfire.net/bank/20060308_bak/sfi9876.asmx', 'extra': '', 'dir': '_i22/2' },
    { 'url': 'http://demo.testfire.net/images/sfi9876.asmx', 'extra': '', 'dir': '_i22/3' },
    { 'url': 'http://demo.testfire.net/pr/sfi9876.asmx', 'extra': '', 'dir': '_i22/4' } ]
  },
  { 'severity': 0, 'type': 10204, 'samples': [
    { 'url': 'http://demo.testfire.net/', 'extra': 'X-AspNet-Version', 'dir': '_i23/0' },
    { 'url': 'http://demo.testfire.net/', 'extra': 'X-Powered-By', 'dir': '_i23/1' },
    { 'url': 'http://demo.testfire.net/%2Fnotfound.aspx%3Faspxerrorpath%3D%2Fsfi9876.asmx/', 'extra': 'X-AspNet-Version', 'dir': '_i23/2' },
    { 'url': 'http://demo.testfire.net/admin/', 'extra': 'X-AspNet-Version', 'dir': '_i23/3' },
    { 'url': 'http://demo.testfire.net/admin/nul.asmx/', 'extra': 'X-AspNet-Version', 'dir': '_i23/4' },
    { 'url': 'http://demo.testfire.net/admin/captcha.aspx', 'extra': 'X-AspNet-Version', 'dir': '_i23/5' },
    { 'url': 'http://demo.testfire.net/admin/login.aspx', 'extra': 'X-AspNet-Version', 'dir': '_i23/6' },
    { 'url': 'http://demo.testfire.net/bank/', 'extra': 'X-AspNet-Version', 'dir': '_i23/7' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/', 'extra': 'X-AspNet-Version', 'dir': '_i23/8' },
    { 'url': 'http://demo.testfire.net/bank/queryxpath.aspx/', 'extra': 'X-AspNet-Version', 'dir': '_i23/9' },
    { 'url': 'http://demo.testfire.net/bank/login.aspx', 'extra': 'X-AspNet-Version', 'dir': '_i23/10' },
    { 'url': 'http://demo.testfire.net/bank/servererror.aspx', 'extra': 'X-AspNet-Version', 'dir': '_i23/11' },
    { 'url': 'http://demo.testfire.net/CustomerServiceRepresentative:CustomerService.asmx/', 'extra': 'X-AspNet-Version', 'dir': '_i23/12' },
    { 'url': 'http://demo.testfire.net/images/', 'extra': 'X-AspNet-Version', 'dir': '_i23/13' },
    { 'url': 'http://demo.testfire.net/pr/', 'extra': 'X-AspNet-Version', 'dir': '_i23/14' },
    { 'url': 'http://demo.testfire.net/rss/', 'extra': 'X-AspNet-Version', 'dir': '_i23/15' },
    { 'url': 'http://demo.testfire.net/static/', 'extra': 'X-AspNet-Version', 'dir': '_i23/16' },
    { 'url': 'http://demo.testfire.net/transfer/', 'extra': 'X-AspNet-Version', 'dir': '_i23/17' } ]
  },
  { 'severity': 0, 'type': 10202, 'samples': [
    { 'url': 'http://demo.testfire.net/', 'extra': 'Microsoft-IIS/6.0', 'dir': '_i24/0' } ]
  },
  { 'severity': 0, 'type': 10201, 'samples': [
    { 'url': 'http://demo.testfire.net/', 'extra': 'ASP.NET_SessionId', 'dir': '_i25/0' },
    { 'url': 'http://demo.testfire.net/', 'extra': 'amSessionId', 'dir': '_i25/1' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx', 'extra': 'lang', 'dir': '_i25/2' },
    { 'url': 'http://demo.testfire.net/bank/customize.aspx/login.aspx', 'extra': 'lang', 'dir': '_i25/3' },
    { 'url': 'http://demo.testfire.net/bank/account.aspx', 'extra': 'amUserId', 'dir': '_i25/4' },
    { 'url': 'http://demo.testfire.net/bank/account.aspx', 'extra': 'amCreditOffer', 'dir': '_i25/5' } ]
  }
];

