#!/bin/sh -e

. /usr/share/debconf/confmodule

case "$1" in
    "configure")
        if [ ! -f "/etc/threadfix/database/threadfix.log" ] && [ ! -f "/etc/threadfix/database/threadfix.properties" ] && [ ! -f "/etc/threadfix/database/threadfix.script" ];
        then
            mkdir -p /etc/threadfix/database
            cp /usr/share/threadfix/threadfix/WEB-INF/classes/threadfix-backup.script /etc/threadfix/database/threadfix.script
            mkdir -p /etc/threadfix/scratch
            chown -R tomcat7:tomcat7 /etc/threadfix
        fi
        ;;
esac

service tomcat7 start

exit 0
