package com.denimgroup.threadfix.framework.impl.rails;

import com.denimgroup.threadfix.framework.ResourceManager;
import com.denimgroup.threadfix.framework.impl.rails.model.RailsRoute;
import org.junit.Test;

import java.io.File;
import java.util.Map;

import static org.junit.Assert.assertTrue;

/**
 * Created by sgerick on 3/9/2015.
 */
public class RailsRoutesParserTest {

    private static final String[][] RAILSGOAT_ROUTES = new String [][] {
        {"GET", "/login"},
        {"GET", "/signup"},
        {"GET", "/logout"},
        {"GET", "/forgot_password"},
        {"GET", "/password_resets"},
        {"POST", "/password_resets"},
        {"GET", "/sessions"},
        {"POST", "/sessions"},
        {"GET", "/sessions/new"},
        {"GET", "/sessions/{id}/edit"},
        {"GET", "/sessions/{id}"},
        {"PUT", "/sessions/{id}"},
        {"DELETE", "/sessions/{id}"},
        {"GET", "/users/{id}/account_settings"},
        {"GET", "/users/{id}/retirement"},
        {"POST", "/users/{id}/retirement"},
        {"GET", "/users/{id}/retirement/new"},
        {"GET", "/users/{id}/retirement/{id}/edit"},
        {"GET", "/users/{id}/retirement/{id}"},
        {"PUT", "/users/{id}/retirement/{id}"},
        {"DELETE", "/users/{id}/retirement/{id}"},
        {"GET", "/users/{id}/paid_time_off"},
        {"POST", "/users/{id}/paid_time_off"},
        {"GET", "/users/{id}/paid_time_off/new"},
        {"GET", "/users/{id}/paid_time_off/{id}/edit"},
        {"GET", "/users/{id}/paid_time_off/{id}"},
        {"PUT", "/users/{id}/paid_time_off/{id}"},
        {"DELETE", "/users/{id}/paid_time_off/{id}"},
        {"GET", "/users/{id}/work_info"},
        {"POST", "/users/{id}/work_info"},
        {"GET", "/users/{id}/work_info/new"},
        {"GET", "/users/{id}/work_info/{id}/edit"},
        {"GET", "/users/{id}/work_info/{id}"},
        {"PUT", "/users/{id}/work_info/{id}"},
        {"DELETE", "/users/{id}/work_info/{id}"},
        {"GET", "/users/{id}/performance"},
        {"POST", "/users/{id}/performance"},
        {"GET", "/users/{id}/performance/new"},
        {"GET", "/users/{id}/performance/{id}/edit"},
        {"GET", "/users/{id}/performance/{id}"},
        {"PUT", "/users/{id}/performance/{id}"},
        {"DELETE", "/users/{id}/performance/{id}"},
        {"GET", "/users/{id}/benefit_forms"},
        {"POST", "/users/{id}/benefit_forms"},
        {"GET", "/users/{id}/benefit_forms/new"},
        {"GET", "/users/{id}/benefit_forms/{id}/edit"},
        {"GET", "/users/{id}/benefit_forms/{id}"},
        {"PUT", "/users/{id}/benefit_forms/{id}"},
        {"DELETE", "/users/{id}/benefit_forms/{id}"},
        {"GET", "/users/{id}/messages"},
        {"POST", "/users/{id}/messages"},
        {"GET", "/users/{id}/messages/new"},
        {"GET", "/users/{id}/messages/{id}/edit"},
        {"GET", "/users/{id}/messages/{id}"},
        {"PUT", "/users/{id}/messages/{id}"},
        {"DELETE", "/users/{id}/messages/{id}"},
        {"POST", "/users/{id}/pay/update_dd_info"},
        {"POST", "/users/{id}/pay/decrypted_bank_acct_num"},
        {"GET", "/users/{id}/pay"},
        {"POST", "/users/{id}/pay"},
        {"GET", "/users/{id}/pay/new"},
        {"GET", "/users/{id}/pay/{id}/edit"},
        {"GET", "/users/{id}/pay/{id}"},
        {"PUT", "/users/{id}/pay/{id}"},
        {"DELETE", "/users/{id}/pay/{id}"},
        {"GET", "/users"},
        {"POST", "/users"},
        {"GET", "/users/new"},
        {"GET", "/users/{id}/edit"},
        {"GET", "/users/{id}"},
        {"PUT", "/users/{id}"},
        {"DELETE", "/users/{id}"},
        {"GET", "/download"},
        {"POST", "/upload"},
        {"GET", "/tutorials/credentials"},
        {"GET", "/tutorials/injection"},
        {"GET", "/tutorials/xss"},
        {"GET", "/tutorials/broken_auth"},
        {"GET", "/tutorials/insecure_dor"},
        {"GET", "/tutorials/csrf"},
        {"GET", "/tutorials/misconfig"},
        {"GET", "/tutorials/exposure"},
        {"GET", "/tutorials/url_access"},
        {"GET", "/tutorials/insecure_components"},
        {"GET", "/tutorials/access_control"},
        {"GET", "/tutorials/ssl_tls"},
        {"GET", "/tutorials/redirects"},
        {"GET", "/tutorials/guard"},
        {"GET", "/tutorials/mass_assignment"},
        {"GET", "/tutorials/gauntlt"},
        {"GET", "/tutorials/logic_flaws"},
        {"GET", "/tutorials/metaprogramming"},
        {"GET", "/tutorials"},
        {"POST", "/tutorials"},
        {"GET", "/tutorials/new"},
        {"GET", "/tutorials/{id}/edit"},
        {"GET", "/tutorials/{id}"},
        {"PUT", "/tutorials/{id}"},
        {"DELETE", "/tutorials/{id}"},
        {"GET", "/schedule/get_pto_schedule"},
        {"GET", "/schedule"},
        {"POST", "/schedule"},
        {"GET", "/schedule/new"},
        {"GET", "/schedule/{id}/edit"},
        {"GET", "/schedule/{id}"},
        {"PUT", "/schedule/{id}"},
        {"DELETE", "/schedule/{id}"},
        {"GET", "/admin/{id}/dashboard"},
        {"GET", "/admin/{id}/get_user"},
        {"POST", "/admin/{id}/delete_user"},
        {"PUT", "/admin/{id}/update_user"},
        {"GET", "/admin/{id}/get_all_users"},
        {"GET", "/admin/{id}/analytics"},
        {"GET", "/admin"},
        {"POST", "/admin"},
        {"GET", "/admin/new"},
        {"GET", "/admin/{id}/edit"},
        {"GET", "/admin/{id}"},
        {"PUT", "/admin/{id}"},
        {"DELETE", "/admin/{id}"},
        {"GET", "/dashboard/home"},
        {"GET", "/dashboard/change_graph"},
        {"GET", "/dashboard"},
        {"POST", "/dashboard"},
        {"GET", "/dashboard/new"},
        {"GET", "/dashboard/{id}/edit"},
        {"GET", "/dashboard/{id}"},
        {"PUT", "/dashboard/{id}"},
        {"DELETE", "/dashboard/{id}"},
        {"GET", "/api/v1/users"},
        {"POST", "/api/v1/users"},
        {"GET", "/api/v1/users/new"},
        {"GET", "/api/v1/users/{id}/edit"},
        {"GET", "/api/v1/users/{id}"},
        {"PUT", "/api/v1/users/{id}"},
        {"DELETE", "/api/v1/users/{id}"},
        {"GET", "/api/v1/mobile"},
        {"POST", "/api/v1/mobile"},
        {"GET", "/api/v1/mobile/new"},
        {"GET", "/api/v1/mobile/{id}/edit"},
        {"GET", "/api/v1/mobile/{id}"},
        {"PUT", "/api/v1/mobile/{id}"},
        {"DELETE", "/api/v1/mobile/{id}"}
    };

    private static final String[][] DISCOURSE_ROUTES = new String [][]{
      //{"Verb", "URI", "Controller#Action"},
        {"GET", "/404", "exceptions#not_found"},
        {"GET", "/404-body", "exceptions#not_found_body"},
        {"GET", "/about", "about#index"},
        {"POST", "/about", "about#create"},
        {"GET", "/about/new", "about#new"},
        {"GET", "/about/{id}/edit", "about#edit"},
        {"GET", "/about/{id}", "about#show"},
        {"PUT", "/about/{id}", "about#update"},
        {"DELETE", "/about/{id}", "about#destroy"},
        {"GET", "/site", "site#site"},
        {"GET", "/site/settings", "site#settings"},
        {"GET", "/site/custom_html", "site#custom_html"},
        {"GET", "/site/banner", "site#banner"},
        {"GET", "/site/emoji", "site#emoji"},
        {"GET", "/site_customizations/{key}", "site_customizations#show"},
        {"GET", "/forums", "forums#index"},
        {"POST", "/forums", "forums#create"},
        {"GET", "/forums/new", "forums#new"},
        {"GET", "/forums/{id}/edit", "forums#edit"},
        {"GET", "/forums/{id}", "forums#show"},
        {"PUT", "/forums/{id}", "forums#update"},
        {"DELETE", "/forums/{id}", "forums#destroy"},
        {"GET", "/srv/status", "forums#status"},
        {"GET", "/admin", "admin/admin#index"},
        {"GET", "/admin/plugins", "admin/plugins#index"},
        {"GET", "/admin/site_settings/category/{id}", "admin/site_settings#index"},
        {"GET", "/admin/site_settings", "admin/site_settings#index"},
        {"POST", "/admin/site_settings", "admin/site_settings#create"},
        {"GET", "/admin/site_settings/new", "admin/site_settings#new"},
        {"GET", "/admin/site_settings/{id}/edit", "admin/site_settings#edit"},
        {"GET", "/admin/site_settings/{id}", "admin/site_settings#show"},
        {"PUT", "/admin/site_settings/{id}", "admin/site_settings#update"},
        {"DELETE", "/admin/site_settings/{id}", "admin/site_settings#destroy"},
        {"GET", "/admin/reports/{type}", "admin/reports#show"},
        {"POST", "/admin/groups/refresh_automatic_groups", "admin/groups#refresh_automatic_groups"},
        {"PUT", "/admin/groups/{id}/members", "admin/groups#add_members"},
        {"DELETE", "/admin/groups/{id}/members", "admin/groups#remove_member"},
        {"GET", "/admin/groups", "admin/groups#index"},
        {"POST", "/admin/groups", "admin/groups#create"},
        {"GET", "/admin/groups/new", "admin/groups#new"},
        {"GET", "/admin/groups/{id}/edit", "admin/groups#edit"},
        {"GET", "/admin/groups/{id}", "admin/groups#show"},
        {"PUT", "/admin/groups/{id}", "admin/groups#update"},
        {"DELETE", "/admin/groups/{id}", "admin/groups#destroy"},
        {"GET", "/admin/groups/{type}", "admin/groups#show"},
        {"GET", "/admin/groups/{type}/{id}", "admin/groups#show"},
        {"GET", "/admin/users/list/{query}", "admin/users#index"},
        {"GET", "/admin/users/ip-info", "admin/users#ip_info"},
        {"DELETE", "/admin/users/delete-others-with-same-ip", "admin/users#delete_other_accounts_with_same_ip"},
        {"GET", "/admin/users/total-others-with-same-ip", "admin/users#total_other_accounts_with_same_ip"},
        {"PUT", "/admin/users/approve-bulk", "admin/users#approve_bulk"},
        {"DELETE", "/admin/users/reject-bulk", "admin/users#reject_bulk"},
        {"PUT", "/admin/users/{id}/suspend", "admin/users#suspend"},
        {"PUT", "/admin/users/{id}/delete_all_posts", "admin/users#delete_all_posts"},
        {"PUT", "/admin/users/{id}/unsuspend", "admin/users#unsuspend"},
        {"PUT", "/admin/users/{id}/revoke_admin", "admin/users#revoke_admin"},
        {"PUT", "/admin/users/{id}/grant_admin", "admin/users#grant_admin"},
        {"POST", "/admin/users/{id}/generate_api_key", "admin/users#generate_api_key"},
        {"DELETE", "/admin/users/{id}/revoke_api_key", "admin/users#revoke_api_key"},
        {"PUT", "/admin/users/{id}/revoke_moderation", "admin/users#revoke_moderation"},
        {"PUT", "/admin/users/{id}/grant_moderation", "admin/users#grant_moderation"},
        {"PUT", "/admin/users/{id}/approve", "admin/users#approve"},
        {"POST", "/admin/users/{id}/refresh_browsers", "admin/users#refresh_browsers"},
        {"POST", "/admin/users/{id}/log_out", "admin/users#log_out"},
        {"PUT", "/admin/users/{id}/activate", "admin/users#activate"},
        {"PUT", "/admin/users/{id}/deactivate", "admin/users#deactivate"},
        {"PUT", "/admin/users/{id}/block", "admin/users#block"},
        {"PUT", "/admin/users/{id}/unblock", "admin/users#unblock"},
        {"PUT", "/admin/users/{id}/trust_level", "admin/users#trust_level"},
        {"PUT", "/admin/users/{id}/trust_level_lock", "admin/users#trust_level_lock"},
        {"PUT", "/admin/users/{id}/primary_group", "admin/users#primary_group"},
        {"POST", "/admin/users/{id}/groups", "admin/users#add_group"},
        {"DELETE", "/admin/users/{id}/groups/{group_id}", "admin/users#remove_group"},
        {"GET", "/admin/users/{id}/badges", "admin/users#badges"},
        {"GET", "/admin/users/{id}/leader_requirements", "admin/users#tl3_requirements"},
        {"GET", "/admin/users/{id}/tl3_requirements", "admin/users#tl3_requirements"},
        {"PUT", "/admin/users/{id}/anonymize", "admin/users#anonymize"},
        {"GET", "/admin/users", "admin/users#index"},
        {"POST", "/admin/users", "admin/users#create"},
        {"GET", "/admin/users/new", "admin/users#new"},
        {"GET", "/admin/users/{id}/edit", "admin/users#edit"},
        {"GET", "/admin/users/{id}", "admin/users#show"},
        {"PUT", "/admin/users/{id}", "admin/users#update"},
        {"DELETE", "/admin/users/{id}", "admin/users#destroy"},
        {"POST", "/admin/users/sync_sso", "admin/users#sync_sso"},
        {"POST", "/admin/users/invite_admin", "admin/users#invite_admin"},
        {"GET", "/admin/impersonate", "admin/impersonate#index"},
        {"POST", "/admin/impersonate", "admin/impersonate#create"},
        {"GET", "/admin/impersonate/new", "admin/impersonate#new"},
        {"GET", "/admin/impersonate/{id}/edit", "admin/impersonate#edit"},
        {"GET", "/admin/impersonate/{id}", "admin/impersonate#show"},
        {"PUT", "/admin/impersonate/{id}", "admin/impersonate#update"},
        {"DELETE", "/admin/impersonate/{id}", "admin/impersonate#destroy"},
        {"POST", "/admin/email/test", "admin/email#test"},
        {"GET", "/admin/email/all", "admin/email#all"},
        {"GET", "/admin/email/sent", "admin/email#sent"},
        {"GET", "/admin/email/skipped", "admin/email#skipped"},
        {"GET", "/admin/email/preview-digest", "admin/email#preview_digest"},
        {"GET", "/admin/email", "admin/email#index"},
        {"POST", "/admin/email", "admin/email#create"},
        {"GET", "/admin/email/new", "admin/email#new"},
        {"GET", "/admin/email/{id}/edit", "admin/email#edit"},
        {"GET", "/admin/email/{id}", "admin/email#show"},
        {"PUT", "/admin/email/{id}", "admin/email#update"},
        {"DELETE", "/admin/email/{id}", "admin/email#destroy"},
        {"GET", "/admin/logs/staff_action_logs", "admin/staff_action_logs#index"},
        {"GET", "/admin/logs/screened_emails", "admin/screened_emails#index"},
        {"DELETE", "/admin/logs/screened_emails/{id}", "admin/screened_emails#destroy"},
        {"POST", "/admin/logs/screened_ip_addresses/roll_up", "admin/screened_ip_addresses#roll_up"},
        {"GET", "/admin/logs/screened_ip_addresses", "admin/screened_ip_addresses#index"},
        {"POST", "/admin/logs/screened_ip_addresses", "admin/screened_ip_addresses#create"},
        {"PUT", "/admin/logs/screened_ip_addresses/{id}", "admin/screened_ip_addresses#update"},
        {"DELETE", "/admin/logs/screened_ip_addresses/{id}", "admin/screened_ip_addresses#destroy"},
        {"GET", "/admin/logs/screened_urls", "admin/screened_urls#index"},
        {"GET", "/admin/logs", "admin/staff_action_logs#index"},
        {"GET", "/admin/customize", "admin/color_schemes#index"},
        {"GET", "/admin/customize/css_html", "admin/site_customizations#index"},
        {"GET", "/admin/customize/colors", "admin/color_schemes#index"},
        {"GET", "/admin/flags", "admin/flags#index"},
        {"GET", "/admin/flags/{filter}", "admin/flags#index"},
        {"POST", "/admin/flags/agree/{id}", "admin/flags#agree"},
        {"POST", "/admin/flags/disagree/{id}", "admin/flags#disagree"},
        {"POST", "/admin/flags/defer/{id}", "admin/flags#defer"},
        {"GET", "/admin/site_customizations", "admin/site_customizations#index"},
        {"POST", "/admin/site_customizations", "admin/site_customizations#create"},
        {"GET", "/admin/site_customizations/new", "admin/site_customizations#new"},
        {"GET", "/admin/site_customizations/{id}/edit", "admin/site_customizations#edit"},
        {"GET", "/admin/site_customizations/{id}", "admin/site_customizations#show"},
        {"PUT", "/admin/site_customizations/{id}", "admin/site_customizations#update"},
        {"DELETE", "/admin/site_customizations/{id}", "admin/site_customizations#destroy"},
        {"GET", "/admin/customize/site_text", "admin/site_text#index"},
        {"POST", "/admin/customize/site_text", "admin/site_text#create"},
        {"GET", "/admin/customize/site_text/new", "admin/site_text#new"},
        {"GET", "/admin/customize/site_text/{id}/edit", "admin/site_text#edit"},
        {"GET", "/admin/customize/site_text/{id}", "admin/site_text#show"},
        {"PUT", "/admin/customize/site_text/{id}", "admin/site_text#update"},
        {"DELETE", "/admin/customize/site_text/{id}", "admin/site_text#destroy"},
        {"GET", "/admin/customize/site_text_types", "admin/site_text_types#index"},
        {"POST", "/admin/customize/site_text_types", "admin/site_text_types#create"},
        {"GET", "/admin/customize/site_text_types/new", "admin/site_text_types#new"},
        {"GET", "/admin/customize/site_text_types/{id}/edit", "admin/site_text_types#edit"},
        {"GET", "/admin/customize/site_text_types/{id}", "admin/site_text_types#show"},
        {"PUT", "/admin/customize/site_text_types/{id}", "admin/site_text_types#update"},
        {"DELETE", "/admin/customize/site_text_types/{id}", "admin/site_text_types#destroy"},
        {"GET", "/admin/customize/user_fields", "admin/user_fields#index"},
        {"POST", "/admin/customize/user_fields", "admin/user_fields#create"},
        {"GET", "/admin/customize/user_fields/new", "admin/user_fields#new"},
        {"GET", "/admin/customize/user_fields/{id}/edit", "admin/user_fields#edit"},
        {"GET", "/admin/customize/user_fields/{id}", "admin/user_fields#show"},
        {"PUT", "/admin/customize/user_fields/{id}", "admin/user_fields#update"},
        {"DELETE", "/admin/customize/user_fields/{id}", "admin/user_fields#destroy"},
        {"GET", "/admin/customize/emojis", "admin/emojis#index"},
        {"POST", "/admin/customize/emojis", "admin/emojis#create"},
        {"GET", "/admin/customize/emojis/new", "admin/emojis#new"},
        {"GET", "/admin/customize/emojis/{id}/edit", "admin/emojis#edit"},
        {"GET", "/admin/customize/emojis/{id}", "admin/emojis#show"},
        {"PUT", "/admin/customize/emojis/{id}", "admin/emojis#update"},
        {"DELETE", "/admin/customize/emojis/{id}", "admin/emojis#destroy"},
        {"GET", "/admin/color_schemes", "admin/color_schemes#index"},
        {"POST", "/admin/color_schemes", "admin/color_schemes#create"},
        {"GET", "/admin/color_schemes/new", "admin/color_schemes#new"},
        {"GET", "/admin/color_schemes/{id}/edit", "admin/color_schemes#edit"},
        {"GET", "/admin/color_schemes/{id}", "admin/color_schemes#show"},
        {"PUT", "/admin/color_schemes/{id}", "admin/color_schemes#update"},
        {"DELETE", "/admin/color_schemes/{id}", "admin/color_schemes#destroy"},
        {"GET", "/admin/version_check", "admin/versions#show"},
        {"GET", "/admin/dashboard/problems", "admin/dashboard#problems"},
        {"GET", "/admin/dashboard", "admin/dashboard#index"},
        {"POST", "/admin/api/key", "admin/api#create_master_key"},
        {"PUT", "/admin/api/key", "admin/api#regenerate_key"},
        {"DELETE", "/admin/api/key", "admin/api#revoke_key"},
        {"GET", "/admin/api", "admin/api#index"},
        {"GET", "/admin/backups/{id}", "admin/backups#show"},
        {"DELETE", "/admin/backups/{id}", "admin/backups#destroy"},
        {"POST", "/admin/backups/{id}/restore", "admin/backups#restore"},
        {"GET", "/admin/backups/logs", "admin/backups#logs"},
        {"GET", "/admin/backups/status", "admin/backups#status"},
        {"GET", "/admin/backups/cancel", "admin/backups#cancel"},
        {"GET", "/admin/backups/rollback", "admin/backups#rollback"},
        {"PUT", "/admin/backups/readonly", "admin/backups#readonly"},
        {"GET", "/admin/backups/upload", "admin/backups#check_backup_chunk"},
        {"POST", "/admin/backups/upload", "admin/backups#upload_backup_chunk"},
        {"GET", "/admin/backups", "admin/backups#index"},
        {"POST", "/admin/backups", "admin/backups#create"},
        {"GET", "/admin/badges/types", "admin/badges#badge_types"},
        {"POST", "/admin/badges/badge_groupings", "admin/badges#save_badge_groupings"},
        {"POST", "/admin/badges/preview", "admin/badges#preview"},
        {"GET", "/admin/badges", "admin/badges#index"},
        {"POST", "/admin/badges", "admin/badges#create"},
        {"GET", "/admin/badges/new", "admin/badges#new"},
        {"GET", "/admin/badges/{id}/edit", "admin/badges#edit"},
        {"GET", "/admin/badges/{id}", "admin/badges#show"},
        {"PUT", "/admin/badges/{id}", "admin/badges#update"},
        {"DELETE", "/admin/badges/{id}", "admin/badges#destroy"},
        {"GET", "/admin/memory_stats", "admin/diagnostics#memory_stats"},
        {"GET", "/admin/dump_heap", "admin/diagnostics#dump_heap"},
        {"GET", "/email_preferences", "email#preferences_redirect"},
        {"GET", "/email/unsubscribe/{key}", "email#unsubscribe"},
        {"POST", "/email/resubscribe/{key}", "email#resubscribe"},
        {"GET", "/session/{id}/become", "session#become"},
        {"POST", "/session/forgot_password", "session#forgot_password"},
        {"POST", "/session", "session#create"},
        {"DELETE", "/session/{id}", "session#destroy"},
        {"GET", "/session/sso", "session#sso"},
        {"GET", "/session/sso_login", "session#sso_login"},
        {"GET", "/session/sso_provider", "session#sso_provider"},
        {"GET", "/session/current", "session#current"},
        {"GET", "/session/csrf", "session#csrf"},
        {"GET", "/composer-messages", "composer_messages#index"},
        {"GET", "/users/check_username", "users#check_username"},
        {"GET", "/users/is_local_username", "users#is_local_username"},
        {"GET", "/users", "users#index"},
        {"POST", "/users", "users#create"},
        {"GET", "/users/new", "users#new"},
        {"GET", "/users/{id}/edit", "users#edit"},
        {"GET", "/static", "static#index"},
        {"POST", "/static", "static#create"},
        {"GET", "/static/new", "static#new"},
        {"GET", "/static/{id}/edit", "static#edit"},
        {"GET", "/static/{id}", "static#show"},
        {"PUT", "/static/{id}", "static#update"},
        {"DELETE", "/static/{id}", "static#destroy"},
        {"POST", "/login", "static#enter"},
        {"GET", "/login", "static#show"},
        {"GET", "/faq", "static#show"},
        {"GET", "/guidelines", "static#show"},
        {"GET", "/tos", "static#show"},
        {"GET", "/privacy", "static#show"},
        {"GET", "/signup", "list#latest"},
        {"POST", "/users/read-faq", "users#read_faq"},
        {"GET", "/users/search/users", "users#search_users"},
        {"GET", "/users/account-created", "users#account_created"},
        {"GET", "/users/password-reset/{token}", "users#password_reset"},
        {"PUT", "/users/password-reset/{token}", "users#password_reset"},
        {"GET", "/users/activate-account/{token}", "users#activate_account"},
        {"PUT", "/users/activate-account/{token}", "users#perform_account_activation"},
        {"GET", "/users/authorize-email/{token}", "users#authorize_email"},
        {"GET", "/users/hp", "users#get_honeypot_value"},
        {"GET", "/my/*path", "users#my_redirect"},
        {"GET", "/user_preferences", "users#user_preferences_redirect"},
        {"GET", "/users/{username}/private-messages", "user_actions#private_messages"},
        {"GET", "/users/{username}/private-messages/{filter}", "user_actions#private_messages"},
        {"GET", "/users/{username}", "users#show"},
        {"PUT", "/users/{username}", "users#update"},
        {"PUT", "/users/{username}/emails", "users#check_emails"},
        {"GET", "/users/{username}/preferences", "users#preferences"},
        {"GET", "/users/{username}/preferences/email", "users#preferences"},
        {"PUT", "/users/{username}/preferences/email", "users#change_email"},
        {"GET", "/users/{username}/preferences/about-me", "users#preferences"},
        {"GET", "/users/{username}/preferences/badge_title", "users#preferences"},
        {"PUT", "/users/{username}/preferences/badge_title", "users#badge_title"},
        {"GET", "/users/{username}/preferences/username", "users#preferences"},
        {"PUT", "/users/{username}/preferences/username", "users#username"},
        {"POST", "/users/{username}/preferences/user_image", "users#upload_user_image"},
        {"DELETE", "/users/{username}/preferences/user_image", "users#destroy_user_image"},
        {"PUT", "/users/{username}/preferences/avatar/pick", "users#pick_avatar"},
        {"GET", "/users/{username}/preferences/card-badge", "users#card_badge"},
        {"PUT", "/users/{username}/preferences/card-badge", "users#update_card_badge"},
        {"GET", "/users/{username}/staff-info", "users#staff_info"},
        {"GET", "/users/{username}/invited", "users#invited"},
        {"POST", "/users/action/send_activation_email", "users#send_activation_email"},
        {"GET", "/users/{username}/activity", "users#show"},
        {"GET", "/users/{username}/activity/{filter}", "users#show"},
        {"GET", "/users/{username}/badges", "users#show"},
        {"GET", "/users/{username}/notifications", "users#show"},
        {"DELETE", "/users/{username}", "users#destroy"},
        {"GET", "/users/by-external/{external_id}", "users#show"},
        {"GET", "/users/{username}/flagged-posts", "users#show"},
        {"GET", "/users/{username}/deleted-posts", "users#show"},
        {"GET", "/user-badges/{username}", "user_badges#username"},
        {"POST", "/user_avatar/{username}/refresh_gravatar", "user_avatars#refresh_gravatar"},
        {"GET", "/letter_avatar/{username}/{size}/{version}.png", "user_avatars#show_letter"},
        {"GET", "/user_avatar/{hostname}/{username}/{size}/{version}.png", "user_avatars#show"},
        {"GET", "/uploads/{site}/{id}/{sha}.{extension}", "uploads#show"},
        {"GET", "/uploads/{site}/{sha}", "uploads#show"},
        {"POST", "/uploads", "uploads#create"},
        {"GET", "/posts", "posts#latest"},
        {"GET", "/posts/by_number/{topic_id}/{post_number}", "posts#by_number"},
        {"GET", "/posts/{id}/reply-history", "posts#reply_history"},
        {"GET", "/posts/{username}/deleted", "posts#deleted_posts"},
        {"GET", "/posts/{username}/flagged", "posts#flagged_posts"},
        {"GET", "/groups/{id}/members", "groups#members"},
        {"GET", "/groups/{id}/posts", "groups#posts"},
        {"GET", "/groups/{id}/counts", "groups#counts"},
        {"PUT", "/groups/{id}/members", "groups#add_members"},
        {"DELETE", "/groups/{id}/members/{username}", "groups#remove_member"},
        {"GET", "/groups", "groups#index"},
        {"POST", "/groups", "groups#create"},
        {"GET", "/groups/new", "groups#new"},
        {"GET", "/groups/{id}/edit", "groups#edit"},
        {"GET", "/groups/{id}", "groups#show"},
        {"PUT", "/groups/{id}", "groups#update"},
        {"DELETE", "/groups/{id}", "groups#destroy"},
        {"GET", "/group/{id}", "redirect(301, /groups/%{id})"},
        {"GET", "/group/{id}/members", "redirect(301, /groups/%{id}/members)"},
        {"PUT", "/posts/{id}/bookmark", "posts#bookmark"},
        {"PUT", "/posts/{id}/wiki", "posts#wiki"},
        {"PUT", "/posts/{id}/post_type", "posts#post_type"},
        {"PUT", "/posts/{id}/rebake", "posts#rebake"},
        {"PUT", "/posts/{id}/unhide", "posts#unhide"},
        {"GET", "/posts/{id}/replies", "posts#replies"},
        {"GET", "/posts/{id}/revisions/latest", "posts#latest_revision"},
        {"GET", "/posts/{id}/revisions/{revision}", "posts#revisions"},
        {"PUT", "/posts/{id}/revisions/{revision}/hide", "posts#hide_revision"},
        {"PUT", "/posts/{id}/revisions/{revision}/show", "posts#show_revision"},
        {"PUT", "/posts/{id}/recover", "posts#recover"},
        {"DELETE", "/posts/destroy_many", "posts#destroy_many"},
        {"GET", "/posts", "posts#index"},
        {"POST", "/posts", "posts#create"},
        {"GET", "/posts/new", "posts#new"},
        {"GET", "/posts/{id}/edit", "posts#edit"},
        {"GET", "/posts/{id}", "posts#show"},
        {"PUT", "/posts/{id}", "posts#update"},
        {"DELETE", "/posts/{id}", "posts#destroy"},
        {"GET", "/notifications", "notifications#recent"},
        {"GET", "/notifications/history", "notifications#history"},
        {"PUT", "/notifications/reset-new", "notifications#reset_new"},
        {"GET", "/auth/{provider}/callback", "users/omniauth_callbacks#complete"},
        {"GET", "/auth/failure", "users/omniauth_callbacks#failure"},
        {"GET", "/clicks/track", "clicks#track"},
        {"GET", "/clicks", "clicks#index"},
        {"POST", "/clicks", "clicks#create"},
        {"GET", "/clicks/new", "clicks#new"},
        {"GET", "/clicks/{id}/edit", "clicks#edit"},
        {"GET", "/clicks/{id}", "clicks#show"},
        {"PUT", "/clicks/{id}", "clicks#update"},
        {"DELETE", "/clicks/{id}", "clicks#destroy"},
        {"GET", "/excerpt", "excerpt#show"},
        {"GET", "/post_actions/users", "post_actions#users"},
        {"POST", "/post_actions/defer_flags", "post_actions#defer_flags"},
        {"GET", "/post_actions", "post_actions#index"},
        {"POST", "/post_actions", "post_actions#create"},
        {"GET", "/post_actions/new", "post_actions#new"},
        {"GET", "/post_actions/{id}/edit", "post_actions#edit"},
        {"GET", "/post_actions/{id}", "post_actions#show"},
        {"PUT", "/post_actions/{id}", "post_actions#update"},
        {"DELETE", "/post_actions/{id}", "post_actions#destroy"},
        {"GET", "/user_actions", "user_actions#index"},
        {"POST", "/user_actions", "user_actions#create"},
        {"GET", "/user_actions/new", "user_actions#new"},
        {"GET", "/user_actions/{id}/edit", "user_actions#edit"},
        {"GET", "/user_actions/{id}", "user_actions#show"},
        {"PUT", "/user_actions/{id}", "user_actions#update"},
        {"DELETE", "/user_actions/{id}", "user_actions#destroy"},
        {"GET", "/badges", "badges#index"},
        {"GET", "/badges/{id}(/{slug})", "badges#show"},
        {"GET", "/user_badges", "user_badges#index"},
        {"POST", "/user_badges", "user_badges#create"},
        {"DELETE", "/user_badges/{id}", "user_badges#destroy"},
        {"GET", "/categories", "categories#index"},
        {"POST", "/categories", "categories#create"},
        {"GET", "/categories/new", "categories#new"},
        {"GET", "/categories/{id}/edit", "categories#edit"},
        {"PUT", "/categories/{id}", "categories#update"},
        {"DELETE", "/categories/{id}", "categories#destroy"},
        {"POST", "/category/uploads", "categories#upload"},
        {"POST", "/category/{category_id}/move", "categories#move"},
        {"POST", "/category/{category_id}/notifications", "categories#set_notifications"},
        {"PUT", "/category/{category_id}/slug", "categories#update_slug"},
        {"GET", "/c/{id}/show", "categories#show"},
        {"GET", "/c/{category}.rss", "list#category_feed"},
        {"GET", "/c/{parent_category}/{category}.rss", "list#category_feed"},
        {"GET", "/c/{category}", "list#category_latest"},
        {"GET", "/c/{category}/none", "list#category_none_latest"},
        {"GET", "/c/{parent_category}/{category}", "list#parent_category_category_latest"},
        {"GET", "/c/{category}/l/top", "list#category_top"},
        {"GET", "/c/{category}/none/l/top", "list#category_none_top"},
        {"GET", "/c/{parent_category}/{category}/l/top", "list#parent_category_category_top"},
        {"GET", "/top/{period}", "list#top_{period}"},
        {"GET", "/c/{category}/l/top/{period}", "list#category_top_{period}"},
        {"GET", "/c/{category}/none/l/top/{period}", "list#category_none_top_{period}"},
        {"GET", "/c/{parent_category}/{category}/l/top/{period}", "list#parent_category_category_top_{period}"},
        {"GET", "/{filter}.rss", "list#{filter}_feed"},
        {"GET", "/{filter}", "list#{filter}"},
        {"GET", "/c/{category}/l/{filter}", "list#category_{filter}"},
        {"GET", "/c/{category}/none/l/{filter}", "list#category_none_{filter}"},
        {"GET", "/c/{parent_category}/{category}/l/{filter}", "list#parent_category_category_{filter}"},
        {"GET", "/category/*path", "categories#redirect"},
        {"GET", "/top", "list#top"},
        {"GET", "/search", "search#query"},
        {"GET", "/t/{id}", "topics#show"},
        {"POST", "/t", "  topics#create"},
        {"PUT", "/t/{id}", "topics#update"},
        {"DELETE", "/t/{id}", "topics#destroy"},
        {"PUT", "/topics/bulk", "topics#bulk"},
        {"PUT", "/topics/reset-new", "topics#reset_new"},
        {"POST", "/topics/timings", "topics#timings"},
        {"GET", "/topics/similar_to", "topics#similar_to"},
        {"GET", "/topics/created-by/{username}", "list#topics_by"},
        {"GET", "/topics/private-messages/{username}", "list#private_messages"},
        {"GET", "/topics/private-messages-sent/{username}", "list#private_messages_sent"},
        {"GET", "/topics/private-messages-unread/{username}", "list#private_messages_unread"},
        {"GET", "/embed/comments", "embed#comments"},
        {"GET", "/embed/count", "embed#count"},
        {"GET", "/t/id_for/{slug}", "topics#id_for_slug"},
        {"GET", "/t/{slug}/{topic_id}/wordpress", "topics#wordpress"},
        {"GET", "/t/{slug}/{topic_id}/moderator-liked", "topics#moderator_liked"},
        {"GET", "/t/{topic_id}/wordpress", "topics#wordpress"},
        {"GET", "/t/{slug}/{topic_id}/summary", "topics#show"},
        {"GET", "/t/{topic_id}/summary", "topics#show"},
        {"PUT", "/t/{slug}/{topic_id}", "topics#update"},
        {"PUT", "/t/{slug}/{topic_id}/star", "topics#star"},
        {"PUT", "/t/{topic_id}/star", "topics#star"},
        {"PUT", "/t/{slug}/{topic_id}/status", "topics#status"},
        {"PUT", "/t/{topic_id}/status", "topics#status"},
        {"PUT", "/t/{topic_id}/clear-pin", "topics#clear_pin"},
        {"PUT", "/t/{topic_id}/re-pin", "topics#re_pin"},
        {"PUT", "/t/{topic_id}/mute", "topics#mute"},
        {"PUT", "/t/{topic_id}/unmute", "topics#unmute"},
        {"PUT", "/t/{topic_id}/autoclose", "topics#autoclose"},
        {"PUT", "/t/{topic_id}/make-banner", "topics#make_banner"},
        {"PUT", "/t/{topic_id}/remove-banner", "topics#remove_banner"},
        {"PUT", "/t/{topic_id}/remove-allowed-user", "topics#remove_allowed_user"},
        {"PUT", "/t/{topic_id}/recover", "topics#recover"},
        {"GET", "/t/{topic_id}/{post_number}", "topics#show"},
        {"GET", "/t/{topic_id}/last", "topics#show"},
        {"GET", "/t/{slug}/{topic_id}.rss", "topics#feed"},
        {"GET", "/t/{slug}/{topic_id}", "topics#show"},
        {"GET", "/t/{slug}/{topic_id}/{post_number}", "topics#show"},
        {"GET", "/t/{slug}/{topic_id}/last", "topics#show"},
        {"GET", "/t/{topic_id}/posts", "topics#posts"},
        {"POST", "/t/{topic_id}/timings", "topics#timings"},
        {"POST", "/t/{topic_id}/invite", "topics#invite"},
        {"POST", "/t/{topic_id}/move-posts", "topics#move_posts"},
        {"POST", "/t/{topic_id}/merge-topic", "topics#merge_topic"},
        {"POST", "/t/{topic_id}/change-owner", "topics#change_post_owners"},
        {"DELETE", "/t/{topic_id}/timings", "topics#destroy_timings"},
        {"PUT", "/t/{topic_id}/bookmark", "topics#bookmark"},
        {"PUT", "/t/{topic_id}/remove_bookmarks", "topics#remove_bookmarks"},
        {"POST", "/t/{topic_id}/notifications", "topics#set_notifications"},
        {"GET", "/p/{post_id}(/{user_id})", "posts#short_link"},
        {"GET", "/posts/{id}/cooked", "posts#cooked"},
        {"GET", "/posts/{id}/expand-embed", "posts#expand_embed"},
        {"GET", "/posts/{id}/raw", "posts#markdown_id"},
        {"GET", "/posts/{id}/raw-email", "posts#raw_email"},
        {"GET", "/raw/{topic_id}(/{post_number})", "posts#markdown_num"},
        {"GET", "/invites/upload", "invites#check_csv_chunk"},
        {"POST", "/invites/upload", "invites#upload_csv_chunk"},
        {"GET", "/invites", "invites#index"},
        {"POST", "/invites", "invites#create"},
        {"GET", "/invites/new", "invites#new"},
        {"GET", "/invites/{id}/edit", "invites#edit"},
        {"GET", "/invites/{id}", "invites#show"},
        {"PUT", "/invites/{id}", "invites#update"},
        {"DELETE", "/invites/{id}", "invites#destroy"},
        {"POST", "/invites/reinvite", "invites#resend_invite"},
        {"POST", "/invites/disposable", "invites#create_disposable_invite"},
        {"GET", "/invites/redeem/{token}", "invites#redeem_disposable_invite"},
        {"DELETE", "/invites", "invites#destroy"},
        {"GET", "/export_csv/export_entity", "export_csv#export_entity"},
        {"GET", "/export_csv/{id}", "export_csv#show"},
        {"GET", "/export_csv", "export_csv#index"},
        {"POST", "/export_csv", "export_csv#create"},
        {"GET", "/export_csv/new", "export_csv#new"},
        {"GET", "/export_csv/{id}/edit", "export_csv#edit"},
        {"GET", "/export_csv/{id}", "export_csv#show"},
        {"PUT", "/export_csv/{id}", "export_csv#update"},
        {"DELETE", "/export_csv/{id}", "export_csv#destroy"},
        {"GET", "/onebox", "onebox#show"},
        {"GET", "/error", "forums#error"},
        {"GET", "/exception", "list#latest"},
        {"GET", "/message-bus/poll", "message_bus#poll"},
        {"GET", "/draft", "draft#show"},
        {"POST", "/draft", "draft#update"},
        {"DELETE", "/draft", "draft#destroy"},
        {"GET", "/cdn_asset/{site}/*path", "static#cdn_asset"},
        {"GET", "/robots.txt", "robots_txt#index"},
        {"GET", "/*url", "permalinks#show"}
    };

//    private static final String[][] GITLAB_BLOB_ROUTES = new String [][]{
//            {"GET", "/{id}/{id}/blob/*id/diff"},
//            {"GET", "/{id}/{id}/blob/*id"},
//            {"DELETE", "/{id}/{id}/blob/*id"},
//    };

    private static final String[][] GITLAB_ROUTES = new String [][]{
      //{"Verb", "URI"},
        {"GET", "/search"},
        {"GET", "/search/autocomplete"},
        {"GET", "/{username}.keys"},
        {"GET", "/help"},
        {"GET", "/help/{category}/{file}"},
        {"GET", "/help/shortcuts"},
        {"GET", "/help/ui"},
        {"GET", "/snippets/{id}/raw"},
        {"GET", "/snippets"},
        {"POST", "/snippets"},
        {"GET", "/snippets/new"},
        {"GET", "/snippets/{id}/edit"},
        {"GET", "/snippets/{id}"},
        {"PUT", "/snippets/{id}"},
        {"DELETE", "/snippets/{id}"},
        {"GET", "/s/{username}"},
        {"GET", "/import/github/status"},
        {"GET", "/import/github/callback"},
        {"GET", "/import/github/jobs"},
        {"POST", "/import/github"},
        {"GET", "/import/github/new"},
        {"GET", "/import/gitlab/status"},
        {"GET", "/import/gitlab/callback"},
        {"GET", "/import/gitlab/jobs"},
        {"POST", "/import/gitlab"},
        {"GET", "/import/gitlab/new"},
        {"GET", "/import/bitbucket/status"},
        {"GET", "/import/bitbucket/callback"},
        {"GET", "/import/bitbucket/jobs"},
        {"POST", "/import/bitbucket"},
        {"GET", "/import/bitbucket/new"},
        {"GET", "/import/gitorious/status"},
        {"GET", "/import/gitorious/callback"},
        {"GET", "/import/gitorious/jobs"},
        {"POST", "/import/gitorious"},
        {"GET", "/import/gitorious/new"},
        {"GET", "/uploads/{model}/{mounted_as}/{id}/{filename}"},
        {"GET", "/uploads/{namespace_id}/{project_id}/{secret}/{filename}"},
        {"GET", "/files/note/{id}/{filename}"},
        {"GET", "/explore/projects/trending"},
        {"GET", "/explore/projects/starred"},
        {"GET", "/explore/projects"},
        {"GET", "/explore/groups"},
        {"GET", "/explore"},
        {"GET", "/public"},
        {"GET", "/public/projects"},
        {"GET", "/admin/users/{id}/keys/{id}"},
        {"DELETE", "/admin/users/{id}/keys/{id}"},
        {"PUT", "/admin/users/{id}/team_update"},
        {"PUT", "/admin/users/{id}/block"},
        {"PUT", "/admin/users/{id}/unblock"},
        {"DELETE", "/admin/users/{id}/remove/{email_id}"},
        {"GET", "/admin/users"},
        {"POST", "/admin/users"},
        {"GET", "/admin/users/new"},
        {"GET", "/admin/users/{id}/edit"},
        {"GET", "/admin/users/{id}"},
        {"PUT", "/admin/users/{id}"},
        {"DELETE", "/admin/users/{id}"},
        {"GET", "/admin/applications"},
        {"POST", "/admin/applications"},
        {"GET", "/admin/applications/new"},
        {"GET", "/admin/applications/{id}/edit"},
        {"GET", "/admin/applications/{id}"},
        {"PUT", "/admin/applications/{id}"},
        {"DELETE", "/admin/applications/{id}"},
        {"PUT", "/admin/groups/{id}/members_update"},
        {"GET", "/admin/groups"},
        {"POST", "/admin/groups"},
        {"GET", "/admin/groups/new"},
        {"GET", "/admin/groups/{id}/edit"},
        {"GET", "/admin/groups/{id}"},
        {"PUT", "/admin/groups/{id}"},
        {"DELETE", "/admin/groups/{id}"},
        {"GET", "/admin/hooks/{id}/test"},
        {"GET", "/admin/hooks"},
        {"POST", "/admin/hooks"},
        {"DELETE", "/admin/hooks/{id}"},
        {"GET", "/admin/broadcast_messages"},
        {"POST", "/admin/broadcast_messages"},
        {"DELETE", "/admin/broadcast_messages/{id}"},
        {"GET", "/admin/logs"},
        {"GET", "/admin/background_jobs"},
        {"GET", "/admin/projects/{id}"},
        {"PUT", "/admin/projects/{id}/{id}/transfer"},
        {"GET", "/admin/projects/{id}/{id}"},
        {"GET", "/admin/application_settings/services"},
        {"POST", "/admin/application_settings/services"},
        {"GET", "/admin/application_settings/services/new"},
        {"GET", "/admin/application_settings/services/{id}/edit"},
        {"GET", "/admin/application_settings/services/{id}"},
        {"PUT", "/admin/application_settings/services/{id}"},
        {"DELETE", "/admin/application_settings/services/{id}"},
        {"GET", "/admin/application_settings"},
        {"PUT", "/admin/application_settings"},
        {"GET", "/admin"},
        {"GET", "/profile/history"},
        {"GET", "/profile/design"},
        {"GET", "/profile/applications"},
        {"PUT", "/profile/reset_private_token"},
        {"PUT", "/profile/update_username"},
        {"GET", "/profile/account"},
        {"PUT", "/profile/account"},
        {"GET", "/profile/notifications"},
        {"PUT", "/profile/notifications"},
        {"PUT", "/profile/password/reset"},
        {"POST", "/profile/password"},
        {"GET", "/profile/password/new"},
        {"GET", "/profile/password/edit"},
        {"PUT", "/profile/password"},
        {"GET", "/profile/keys"},
        {"POST", "/profile/keys"},
        {"GET", "/profile/keys/new"},
        {"GET", "/profile/keys/{id}/edit"},
        {"GET", "/profile/keys/{id}"},
        {"PUT", "/profile/keys/{id}"},
        {"DELETE", "/profile/keys/{id}"},
        {"GET", "/profile/emails"},
        {"POST", "/profile/emails"},
        {"DELETE", "/profile/emails/{id}"},
        {"DELETE", "/profile/avatar"},
        {"GET", "/profile"},
        {"PUT", "/profile"},
        {"GET", "/u/{username}/calendar"},
        {"GET", "/u/{username}"},
        {"GET", "/dashboard/issues"},
        {"GET", "/dashboard/merge_requests"},
        {"GET", "/dashboard/milestones"},
        {"GET", "/dashboard/milestones/{id}"},
        {"GET", "/dashboard/groups"},
        {"GET", "/dashboard/projects/starred"},
        {"GET", "/dashboard"},
        {"GET", "/groups/{id}/issues"},
        {"GET", "/groups/{id}/merge_requests"},
        {"GET", "/groups/{id}/projects"},
        {"GET", "/groups/{id}/group_members"},
        {"POST", "/groups/{id}/group_members"},
        {"PUT", "/groups/{id}/group_members/{id}"},
        {"DELETE", "/groups/{id}/group_members/{id}"},
        {"DELETE", "/groups/{id}/avatar"},
        {"GET", "/groups/{id}/milestones"},
        {"GET", "/groups/{id}/milestones/{id}"},
        {"PUT", "/groups/{id}/milestones/{id}"},
        {"GET", "/groups"},
        {"POST", "/groups"},
        {"GET", "/groups/new"},
        {"GET", "/groups/{id}/edit"},
        {"GET", "/groups/{id}"},
        {"PUT", "/groups/{id}"},
        {"DELETE", "/groups/{id}"},
        {"POST", "/projects"},
        {"GET", "/projects/new"},
        /*  "devise_for :users" creates the /users/* routes using Devise
         *      (Devise is a MVC authentication framework for Rails)
        {"GET", "/users/sign_in"},
        {"POST", "/users/sign_in"},
        {"DELETE", "/users/sign_out"},
        {"GET", "/users/auth/{provider}"},
        {"GET", "/users/auth/{action}/callback"},
        {"POST", "/users/password"},
        {"GET", "/users/password/new"},
        {"GET", "/users/password/edit"},
        {"PUT", "/users/password"},
        {"GET", "/users/cancel"},
        {"POST", "/users"},
        {"GET", "/users/sign_up"},
        {"GET", "/users/edit"},
        {"PUT", "/users"},
        {"DELETE", "/users"},
        {"POST", "/users/confirmation"},
        {"GET", "/users/confirmation/new"},
        {"GET", "/users/confirmation"},
        {"GET", "/users/auth/{provider}/omniauth_error"},
          */
        {"GET", "/"},
        {"PUT", "/{id}/{id}/transfer"},
        {"POST", "/{id}/{id}/archive"},
        {"POST", "/{id}/{id}/unarchive"},
        {"POST", "/{id}/{id}/toggle_star"},
        {"POST", "/{id}/{id}/markdown_preview"},
        {"GET", "/{id}/{id}/autocomplete_sources"},
        {"GET", "/{id}/{id}/new/*id"},
        {"POST", "/{id}/{id}/create/*id"},
        {"GET", "/{id}/{id}/edit/*id"},
        {"PUT", "/{id}/{id}/update/*id"},
        {"POST", "/{id}/{id}/preview/*id"},
        {"GET", "/{id}/{id}/blob/*id/diff"},
        {"GET", "/{id}/{id}/blob/*id"},
        {"DELETE", "/{id}/{id}/blob/*id"},
        {"GET", "/{id}/{id}/raw/*id"},
        {"GET", "/{id}/{id}/tree/*id"},
        {"GET", "/{id}/{id}/avatar"},
        {"DELETE", "/{id}/{id}/avatar"},
        {"GET", "/{id}/{id}/commit/{id}/branches"},
        {"GET", "/{id}/{id}/commit/{id}"},
        {"GET", "/{id}/{id}/commits/{id}"},
        {"GET", "/{id}/{id}/compare"},
        {"POST", "/{id}/{id}/compare"},
        {"GET", "/{id}/{id}/blame/*id"},
        {"GET", "/{id}/{id}/network/{id}"},
        {"GET", "/{id}/{id}/graphs/{id}/commits"},
        {"GET", "/{id}/{id}/graphs/{id}"},
        {"GET", "/{id}/{id}/compare/{from}...{to}"},
        {"GET", "/{id}/{id}/snippets/{id}/raw"},
        {"GET", "/{id}/{id}/snippets"},
        {"POST", "/{id}/{id}/snippets"},
        {"GET", "/{id}/{id}/snippets/new"},
        {"GET", "/{id}/{id}/snippets/{id}/edit"},
        {"GET", "/{id}/{id}/snippets/{id}"},
        {"PUT", "/{id}/{id}/snippets/{id}"},
        {"DELETE", "/{id}/{id}/snippets/{id}"},
        {"GET", "/{id}/{id}/wikis/pages"},
        {"PUT", "/{id}/{id}/wikis/{id}"},
        {"GET", "/{id}/{id}/wikis/git_access"},
        {"GET", "/{id}/{id}/wikis/{id}/history"},
        {"POST", "/{id}/{id}/wikis"},
        {"GET", "/{id}/{id}/wikis/{id}/edit"},
        {"GET", "/{id}/{id}/wikis/{id}"},
        {"DELETE", "/{id}/{id}/wikis/{id}"},
        {"GET", "/{id}/{id}/repository/archive"},
        {"POST", "/{id}/{id}/repository"},
        {"GET", "/{id}/{id}/repository"},
        {"GET", "/{id}/{id}/services/{id}/test"},
        {"GET", "/{id}/{id}/services"},
        {"GET", "/{id}/{id}/services/{id}/edit"},
        {"PUT", "/{id}/{id}/services/{id}"},
        {"PUT", "/{id}/{id}/deploy_keys/{id}/enable"},
        {"PUT", "/{id}/{id}/deploy_keys/{id}/disable"},
        {"GET", "/{id}/{id}/deploy_keys"},
        {"POST", "/{id}/{id}/deploy_keys"},
        {"GET", "/{id}/{id}/deploy_keys/new"},
        {"GET", "/{id}/{id}/deploy_keys/{id}/edit"},
        {"GET", "/{id}/{id}/deploy_keys/{id}"},
        {"PUT", "/{id}/{id}/deploy_keys/{id}"},
        {"DELETE", "/{id}/{id}/deploy_keys/{id}"},
        {"POST", "/{id}/{id}/fork"},
        {"GET", "/{id}/{id}/fork/new"},
        {"POST", "/{id}/{id}/import"},
        {"GET", "/{id}/{id}/import/new"},
        {"GET", "/{id}/{id}/import"},
        {"GET", "/{id}/{id}/refs/switch"},
        {"GET", "/{id}/{id}/refs/{id}/logs_tree"},
        {"GET", "/{id}/{id}/refs/{id}/logs_tree/{path}"},
        {"GET", "/{id}/{id}/merge_requests/{id}/diffs"},
        {"POST", "/{id}/{id}/merge_requests/{id}/automerge"},
        {"GET", "/{id}/{id}/merge_requests/{id}/automerge_check"},
        {"GET", "/{id}/{id}/merge_requests/{id}/ci_status"},
        {"POST", "/{id}/{id}/merge_requests/{id}/toggle_subscription"},
        {"GET", "/{id}/{id}/merge_requests/branch_from"},
        {"GET", "/{id}/{id}/merge_requests/branch_to"},
        {"GET", "/{id}/{id}/merge_requests/update_branches"},
        {"GET", "/{id}/{id}/merge_requests"},
        {"POST", "/{id}/{id}/merge_requests"},
        {"GET", "/{id}/{id}/merge_requests/new"},
        {"GET", "/{id}/{id}/merge_requests/{id}/edit"},
        {"GET", "/{id}/{id}/merge_requests/{id}"},
        {"PUT", "/{id}/{id}/merge_requests/{id}"},
        {"GET", "/{id}/{id}/branches"},
        {"POST", "/{id}/{id}/branches"},
        {"GET", "/{id}/{id}/branches/new"},
        {"DELETE", "/{id}/{id}/branches/{id}"},
        {"GET", "/{id}/{id}/tags"},
        {"POST", "/{id}/{id}/tags"},
        {"GET", "/{id}/{id}/tags/new"},
        {"DELETE", "/{id}/{id}/tags/{id}"},
        {"GET", "/{id}/{id}/protected_branches"},
        {"POST", "/{id}/{id}/protected_branches"},
        {"PUT", "/{id}/{id}/protected_branches/{id}"},
        {"DELETE", "/{id}/{id}/protected_branches/{id}"},
        {"GET", "/{id}/{id}/hooks/{id}/test"},
        {"GET", "/{id}/{id}/hooks"},
        {"POST", "/{id}/{id}/hooks"},
        {"DELETE", "/{id}/{id}/hooks/{id}"},
        {"PUT", "/{id}/{id}/milestones/{id}/sort_issues"},
        {"PUT", "/{id}/{id}/milestones/{id}/sort_merge_requests"},
        {"GET", "/{id}/{id}/milestones"},
        {"POST", "/{id}/{id}/milestones"},
        {"GET", "/{id}/{id}/milestones/new"},
        {"GET", "/{id}/{id}/milestones/{id}/edit"},
        {"GET", "/{id}/{id}/milestones/{id}"},
        {"PUT", "/{id}/{id}/milestones/{id}"},
        {"POST", "/{id}/{id}/labels/generate"},
        {"GET", "/{id}/{id}/labels"},
        {"POST", "/{id}/{id}/labels"},
        {"GET", "/{id}/{id}/labels/new"},
        {"GET", "/{id}/{id}/labels/{id}/edit"},
        {"GET", "/{id}/{id}/labels/{id}"},
        {"PUT", "/{id}/{id}/labels/{id}"},
        {"DELETE", "/{id}/{id}/labels/{id}"},
        {"POST", "/{id}/{id}/issues/{id}/toggle_subscription"},
        {"POST", "/{id}/{id}/issues/bulk_update"},
        {"GET", "/{id}/{id}/issues"},
        {"POST", "/{id}/{id}/issues"},
        {"GET", "/{id}/{id}/issues/new"},
        {"GET", "/{id}/{id}/issues/{id}/edit"},
        {"GET", "/{id}/{id}/issues/{id}"},
        {"PUT", "/{id}/{id}/issues/{id}"},
        {"DELETE", "/{id}/{id}/project_members/leave"},
        {"GET", "/{id}/{id}/project_members/import"},
        {"POST", "/{id}/{id}/project_members/apply_import"},
        {"GET", "/{id}/{id}/project_members"},
        {"POST", "/{id}/{id}/project_members"},
        {"GET", "/{id}/{id}/project_members/{id}"},
        {"PUT", "/{id}/{id}/project_members/{id}"},
        {"DELETE", "/{id}/{id}/project_members/{id}"},
        {"DELETE", "/{id}/{id}/notes/{id}/delete_attachment"},
        {"GET", "/{id}/{id}/notes"},
        {"POST", "/{id}/{id}/notes"},
        {"PUT", "/{id}/{id}/notes/{id}"},
        {"DELETE", "/{id}/{id}/notes/{id}"},
        {"GET", "/{id}/{id}/uploads/{secret}/{filename}"},
        {"POST", "/{id}/{id}/uploads"},
        {"GET", "/{id}/{id}/edit"},
        {"GET", "/{id}/{id}"},
        {"PUT", "/{id}/{id}"},
        {"DELETE", "/{id}/{id}"},
        {"GET", "/{id}"}
    };

    @Test
    public void testRailsGoatRoutesParser() {
        File f = ResourceManager.getRailsFile("railsgoat_routes.rb");
        assert(f.exists());

        //System.err.println("parsing "+f.getAbsolutePath() );
        Map<String, RailsRoute> mappings = RailsRoutesParser.parse(f);
        //System.err.println( System.lineSeparator() + "Parse done." + System.lineSeparator());
        /* for (String s : mappings) {
            System.err.println(s);
        }*/
        compareRoutes(RAILSGOAT_ROUTES, mappings);
    }

    @Test
    public void testDiscourseRoutesParser() {
        File f = ResourceManager.getRailsFile("discource_routes.rb");
        assert(f.exists());
        // System.err.println("parsing "+f.getAbsolutePath() );
        Map<String, RailsRoute> mappings = RailsRoutesParser.parse(f);
        // System.err.println( System.lineSeparator() + "Parse done." + System.lineSeparator());
        // for (String s : mappings) {
        //     System.err.println(s);
        // }
        compareRoutes(DISCOURSE_ROUTES, mappings);
    }

    @Test
    public void testGitlabRoutesParser() throws Exception {
        File f = ResourceManager.getRailsFile("gitlab_routes.rb");
        assert(f.exists());
//        System.err.println("parsing "+f.getAbsolutePath() );
        Map<String, RailsRoute> mappings = RailsRoutesParser.parse(f);
//        for (String s : mappings) {
//            System.err.println(s);
//        }
//        System.err.println( System.lineSeparator() + "Parse done." + System.lineSeparator());
      compareRoutes(GITLAB_ROUTES, mappings);
    }

    private void compareRoutes( String[][] testData, Map<String, RailsRoute> routeMap) {
        boolean found;
        for (String[] testRoute : testData) {
            found = false;
            for (RailsRoute route : routeMap.values()) {
                String url = route.getUrl();
                for (String method : route.getHttpMethods()) {
                    String foundRoute = method + ": " + url;
                    if ( (testRoute[0] + ": " + testRoute[1]).equals(foundRoute) ) {
                        found = true;
                        break;
                    }
                }

            }
            assertTrue("testRoute not found in returned list: " + testRoute[0] + ": " + testRoute[1], found);
        }
    }


}

