package com.denimgroup.threadfix.service.framework;

import java.io.File;

import org.eclipse.jgit.lib.Repository;

import com.denimgroup.threadfix.data.entities.Application;
import com.denimgroup.threadfix.service.repository.GitService;

public class URLCalculatorFactory {
	
	private static final String baseDirectory = "C:\\test\\scratch\\";

	// TODO add more appropriate field to Application object
	// the reason for not doing it now is that 1.2 changes will be easier to absorb if we wait
	public static AbstractURLCalculator getAppropriateCalculator(Application application) {
		if (application == null || application.getUrl() == null) {
			return null;
		}
		
		File applicationDirectory = new File(baseDirectory + application.getId());
		
		Repository repo = GitService.cloneGitTreeToDirectory(application.getUrl(), applicationDirectory);
		
		if (repo != null && repo.getWorkTree() != null && repo.getWorkTree().exists()) {
			File webXML = new ProjectDirectory(repo.getWorkTree()).findWebXML();
			if (webXML != null && webXML.exists()) {
				ServletMappings mappings = WebXMLParser.getServletMappings(webXML);
				
				if (mappings != null) {
					
					// TODO for now we pass the application name as the root. 
					// Down the road we'll want this to be supplied from a form or autogenerated.
					switch (mappings.guessApplicationType()) {
						case JSP:
							return new JSPURLCalculator(mappings, repo.getWorkTree(), application.getName());
						case SPRING_MVC:
							return new SpringURLCalculator(mappings, repo.getWorkTree(), application.getName());
						default:
							return new DefaultURLCalculator(mappings, repo.getWorkTree(), application.getName());
					}
				}
			}
		}
		
		return null;
	}
	
}
